asm/cluster/cluster.yaml, asm/cluster/istio-operator.yaml, asm/cluster/nodepool.yaml
Use a longer cluster name instead.
=> Reduce the chance of hitting kpt token replacement issue.

asm/cluster/cluster.yaml, asm/cluster/istio-operator.yaml, asm/cluster/nodepool.yaml
workaround https://github.com/GoogleContainerTools/kpt/issues/224.
=> Rename template variables to work around a replacement bug

asm/cluster/istio-operator.yaml
=> Update to use 1.4.7

.gitignore, asm-patch/README.md, asm-patch/kustomization.yaml, asm-patch/patches/cluster-patch.yaml, asm-patch/patches/nodepool-patch.yaml, asm-patch/resources/enable-services.yaml, asm-patch/resources/istio-operator.yaml, asm-patch/resources/kustomization.yaml, asm-patch/resources/namespace.yaml
The patch package is used to enable ASM on an existing cluster.
=> Add asm-patch packages

asm-patch/Kptfile, asm-patch/kustomization.yaml, asm-patch/patches/cluster-patch.yaml, asm-patch/patches/nodepool-patch.yaml, asm-patch/resources/enable-services.yaml, asm-patch/resources/istio-operator.yaml, asm-patch/resources/namespace.yaml
PartialSetter is deprecrated and replaced by kpt substition
=> Migrate kpt setter to openAPI.

asm/cluster/istio-operator.yaml
Fixes the security issue, CVE-2020-10739
=> Update to 1.4.9-asm.1

asm-patch/resources/istio-operator.yaml, asm/cluster/istio-operator.yaml
Reverts GoogleCloudPlatform/anthos-service-mesh-packages#70
=> Revert "Enable stackdriver tracing by default"

asm-patch/Kptfile, asm-patch/resources/istio-operator.yaml, asm-primary/Kptfile, asm-primary/cluster/istio-operator.yaml, asm/Kptfile, asm/cluster/cluster.yaml, asm/cluster/istio-operator.yaml
Adding pilot env SPIFFE_BUNDLE_ENDPOINTS
=> Adding pilot env SPIFFE_BUNDLE_ENDPOINTS

asm/cluster/istio-operator.yaml
@elfinhe Please review. Thanks!
=> Upgrade to asm 1.6.4

asm/Kptfile, asm/trafficdirector/roles.yaml, asm/trafficdirector/td-configmap-injection.yaml, asm/trafficdirector/td-configmap-mesh.yaml, asm/trafficdirector/td-gateway.yaml, asm/trafficdirector/td-istiod-asm-rbac.yaml, asm/trafficdirector/td-istiod-asm.yaml, cluster/Kptfile, cluster/cluster/cluster.yaml, project/project/enable-services.yaml
Adds support for 1.6 series ASM images, enable security beta by default, and clean up some install issues.
=> Updating to support 1.6 series images

asm/trafficdirector/td-configmap-injection.yaml, asm/trafficdirector/td-gateway.yaml
=> ASM MCP - Remove unnecessary env var

cluster/Kptfile, cluster/cluster/cluster.yaml
Bumping up the initialNodeCount from 2 to 5 because Hipster app needs 5 nodes.
=> Update initialNodeCount to 5, adjust autoscale sizes

cluster/Kptfile, cluster/cluster/cluster.yaml
Make initialNodeCount settable with kpt as "gcloud.container.nodepool.initial-node-count".
=> Make initialNodeCount settable with kpt

asm-citadel/Kptfile, asm-citadel/cluster/cluster.yaml, asm-citadel/cluster/istio-operator.yaml, asm-citadel/cluster/nodepool.yaml, asm-citadel/project/enable-services.yaml, asm-patch-citadel/Kptfile, asm-patch-citadel/README.md, asm-patch-citadel/kustomization.yaml, asm-patch-citadel/patches/cluster-patch.yaml, asm-patch-citadel/patches/nodepool-patch.yaml, asm-patch-citadel/resources/enable-services.yaml, asm-patch-citadel/resources/istio-operator.yaml, asm-patch-citadel/resources/kustomization.yaml, asm-patch-citadel/resources/namespace.yaml
More discussions in https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/103
=> release-1.6: support to use citadel

asm-citadel/Kptfile, asm-citadel/cluster/istio-operator.yaml, asm-patch-citadel/Kptfile, asm-patch-citadel/resources/istio-operator.yaml, asm-patch/Kptfile, asm-patch/resources/istio-operator.yaml, asm/Kptfile, asm/cluster/istio-operator.yaml
@elfinhe Not sure if I set the setter correctly, ptal, thanks!
I will cherry-pick this to release-1.7 once this is merged.
=> Add control plane monitoring option into asm operator file

asm-citadel/Kptfile, asm-citadel/cluster/istio-operator.yaml, asm-patch-citadel/Kptfile, asm-patch-citadel/resources/istio-operator.yaml, asm-patch/Kptfile, asm-patch/resources/istio-operator.yaml, asm/Kptfile, asm/cluster/istio-operator.yaml
* add control plane monitoring option into asm operator file
* update
=> Add control plane monitoring option into asm operator file (#105)

asm-patch/Kptfile, asm-patch/resources/istio/istio-operator.yaml, asm/Kptfile, asm/istio/istio-operator.yaml, pkg/Kptfile, pkg/istio-citadel/istio-operator.yaml, pkg/istio/istio-operator.yaml
Cherry pick control plane monitoring option into master.
=> [Cherrypick] Add control plane monitoring option into asm operator file (#105) (#110)

asm-patch/Kptfile, asm-patch/resources/istio-operator.yaml, asm/Kptfile, asm/cluster/istio-operator.yaml
=> Update tag to 1.5.9-asm.0

README.md, asm-citadel/Kptfile, asm-citadel/cluster/istio-operator.yaml, asm-patch-citadel/Kptfile, asm-patch-citadel/resources/istio-operator.yaml, asm-patch/Kptfile, asm-patch/resources/istio-operator.yaml, asm/Kptfile, asm/cluster/istio-operator.yaml
Update the tags for 1.6.8-asm.0 and cherry-pick changes for citadel
=> Update the tags for 1.6.8-asm.0 and cherry-pick changes for citadel

asm-patch/Kptfile, asm-patch/resources/istio/istio-operator.yaml, asm/Kptfile, asm/cluster/cluster.yaml, asm/istio/istio-operator.yaml, pkg/Kptfile, pkg/cluster/cluster.yaml, pkg/istio/istio-operator.yaml
Using the same kpt design in release-1.6-asm for the master branch.
Changes are made in pkg folder. The updates in asm, asm-patch are generated by running make all.
=> update pkg to support multiproject profile

asm-patch/Kptfile, asm/Kptfile, asm/istio/options/multicluster.yaml, pkg/Kptfile, pkg/istio/options/multicluster.yaml
Update clusterID to be DNS compliant
=> Update clusterID to be DNS compliant

asm-patch/Kptfile, asm-patch/canonical-service/controller.yaml, asm-patch/resources/kustomization.yaml, asm/Kptfile, asm/canonical-service/controller.yaml
As promised, here is the same changes as https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/136, only now merging them to master instead of the 1.7 release.
=> add canonical-service to master branch

scripts/asm-installer/Dockerfile, scripts/asm-installer/README.md, scripts/asm-installer/cloudbuild.yaml, scripts/asm-installer/install_asm, scripts/asm-installer/tests/common.sh, scripts/asm-installer/tests/fake_gcloud, scripts/asm-installer/tests/fake_kubectl, scripts/asm-installer/tests/run_basic_suite, scripts/asm-installer/tests/run_cli_tests, scripts/asm-installer/tests/run_migration_suite_citadel, scripts/asm-installer/tests/run_migration_suite_meshca
Fix PR #140 after picking the wrong branch
=> Initial script release

scripts/asm-installer/install_asm
* Print when starting the installation
* Make final messages more prominent to easily tell them from other output
* Add links to documentation
* Changed "Next" to "To finish installation" to make it clearer that sidecar injection is a required part of installation
=> Add more detail to success messages

scripts/asm-installer/cloudbuild.yaml, scripts/asm-installer/tests/common.sh, scripts/asm-installer/tests/run_basic_suite, scripts/asm-installer/tests/run_migration_suite_citadel, scripts/asm-installer/tests/run_migration_suite_meshca
=> Clean up GCP resources better

scripts/asm-installer/install_asm, scripts/asm-installer/tests/common.sh
* Small amount of refactoring
* Don't delete tmpdir if a user is running vs. service account
* Extra info in the outro message
=> Save downloaded packages if user runs script

scripts/asm-installer/install_asm
=> Remove workaround

scripts/asm-installer/Dockerfile, scripts/asm-installer/README.md, scripts/asm-installer/cloudbuild.yaml, scripts/asm-installer/install_asm, scripts/asm-installer/tests/common.sh, scripts/asm-installer/tests/fake_gcloud, scripts/asm-installer/tests/fake_kubectl, scripts/asm-installer/tests/run_basic_suite, scripts/asm-installer/tests/run_cli_tests, scripts/asm-installer/tests/run_migration_suite_citadel, scripts/asm-installer/tests/run_migration_suite_meshca
The script is no longer pinned to 1.6, so this commit introduces it to master to continue development. This will allow the release-1.6-asm branch to be much more stable.
d1c4fb9 was generated by running `git merge release-1.6-asm scripts/` on the master branch, so 7293b0b has the only code that needs to be reviewed.
=> Merge install_asm into master

scripts/asm-installer/README.md, scripts/asm-installer/cloudbuild.yaml, scripts/asm-installer/install_asm, scripts/asm-installer/tests/common.sh, scripts/asm-installer/tests/run_basic_suite, scripts/asm-installer/tests/run_cli_tests, scripts/asm-installer/tests/run_migration_suite_citadel, scripts/asm-installer/tests/run_migration_suite_meshca
These are necessary for cloud build to run ci properly
=> Add environment variables to cloudbuild.yaml

scripts/asm-installer/install_asm
Cherry-pick iam bug fix onto release-1.6-asm
=> Fix iam bindings (#174)

scripts/asm-installer/install_asm
=> Apply multicluster manifest automatically

asm/Kptfile, asm/cluster/istio-operator.yaml
* see release notes: https://cloud.google.com/service-mesh/docs/release-notes
* update email for CLA
=> update ASM versions to 1.6.11-asm.1

scripts/asm-installer/install_asm
This was a silly infinite loop.
=> Remove retries for gcloud

scripts/asm-installer/install_asm
Cherry-pick of #220 for release branch
=> Remove retries for gcloud (#220)

scripts/asm-installer/install_asm
=> Clarify revision requirements in outro

asm/Kptfile, asm/istiod-service.yaml
=> Add istiod service to fix validation (#231)

scripts/asm-installer/install_asm
=> Use comma as cluster label delimiter

scripts/asm-installer/install_asm
Changes "readlink" to "stat" on Mac.
Fixes #258
=> Add Mac compatibility

scripts/asm-installer/cloudbuild.yaml, scripts/asm-installer/install_asm, scripts/asm-installer/tests/run_print_config_test
Also fixes a bug that slipped into master that prevents optional yaml files from being appended.
=> Use istioctl profile dump for print-config

scripts/asm-installer/install_asm
This PR is per the request of avoiding IDNS naming externally
=> Update Hub IDNS with Hub Workload Identity Pool

asm/cluster/nodepool.yaml
Adding autoRepair and autoUpgrade for anthoscli new cluster creation
=> Adding autoRepair and autoUpgrade for anthoscli new cluster creation

scripts/asm-installer/cloudbuild.yaml, scripts/asm-installer/install_asm
=> Use -K with curl instead of @-

asm/istio/istio-operator.yaml
Reverts GoogleCloudPlatform/anthos-service-mesh-packages#286
=> Revert "remove duplicate trustdomain entry"

scripts/asm-installer/install_asm
Add --skip-confirmation to skip the newly added condition for manual confirm
=> Add --skip-confirmation to skip the newly added condition for manual confirm

asm/istio/istio-operator.yaml
=> update tag for asm 1.8.1

scripts/asm-installer/cloudbuild.yaml, scripts/asm-installer/install_asm, scripts/asm-installer/tests/fake_gcloud, scripts/asm-installer/tests/run_basic_suite_managed, scripts/asm-installer/tests/run_cli_tests
This shouldn't be merged until cloudbuild.yaml is fixed back
=> Add functionality for managed control plane

scripts/asm-installer/install_asm
=> Print folder name when creating tmpdir

scripts/asm-installer/install_asm, scripts/asm-installer/tests/fake_gcloud
Installation script changes to integrate ASM with Google Certificate Authority Service - https://cloud.google.com/certificate-authority-service
=> Private CA: Install script integration changes

asm/istio/istio-operator.yaml, asm/istio/options/vm.yaml
Add the operator files for VM support.
=> Add VM option

asm/Kptfile, asm/canonical-service/controller.yaml, asm/istio/istio-operator.yaml, scripts/asm-installer/install_asm
=> Bump version

scripts/asm-installer/install_asm
Hopefully this will prevent some customers from needing to hit every
error message one at a time.
=> Add -e flag to error messages.

scripts/asm-installer/install_asm
Ref: #377
@zerobfd, I have made some changes. Please let me know if I need to change anything.
=> unique name for clusterrolebinding

scripts/asm-installer/install_asm
Apparently this matters sometimes?
=> Capitalize gcloud query AND

asm/Kptfile, asm/istio/istio-operator.yaml, scripts/asm-installer/cloudbuild-master.yaml, scripts/asm-installer/install_asm, scripts/asm-installer/tests/common.sh
Also adds default tag in istio-operator for manual installation
=> Install base client-side for MCP

asm/istio/options/multicloud.yaml, asm/istio/options/multicluster.yaml, asm/istio/options/multiproject.yaml
These got deleted in a bad merge I think, re-adding them for compatibility.
=> Fix bad merge and readd yaml

asm/Kptfile
Split the PR so that the test will pass for the following PR.
=> Add setter for managed control plane

asm/Kptfile
Cherry-pick from master to release-1.8-asm
=> Add setter for managed control plane (#394)

scripts/asm-installer/install_asm
=> Remove --force-conflicts flag

scripts/asm-installer/cloudbuild-staging.yaml, scripts/asm-installer/install_asm, scripts/asm-installer/tests/run_print_config_test
* Work around istioctl bug with multi component yaml files
* Add csplit to CLI dependency list
=> Work around istioctl bug with multi component yaml files (#405)

scripts/asm-installer/install_asm
=> Not to apply istiod svc when _CI_NO_REVISION=1

scripts/asm-installer/install_asm
=> Allow cluster to be registered in a different project

asm/vm/asm_vm
=> [VM Script] Allow CI to use different image tag

asm/Kptfile, asm/istio/istio-operator.yaml, asm/istio/options/managed-control-plane.yaml, asm/istio/options/revisioned-custom-ingressgateway.yaml, scripts/asm-installer/install_asm, scripts/asm-installer/tests/fake_gcloud, scripts/asm-installer/tests/run_cli_tests, scripts/asm-installer/tests/run_print_config_test
Bugfixes and stability improvements
=> Merge staging 1.8 into release

scripts/asm-installer/cloudbuild-flaky.yaml, scripts/asm-installer/cloudbuild-master.yaml, scripts/asm-installer/cloudbuild.yaml
This will unblock development for known flaky tests that aren't for core functionality.
=> Remove symlink, move flaky test to separate trigger

scripts/asm-installer/install_asm, scripts/asm-installer/tests/fake_gcloud
Verified that after changing `fake_gcloud` that `run_cli_tests` failed, and then started passing after the change.
=> Do not block validation on asmv label

asm/istio/istio-operator.yaml, scripts/asm-installer/install_asm, scripts/asm-installer/tests/common.sh, scripts/asm-installer/tests/fake_gcloud, scripts/asm-installer/tests/fake_kubectl, scripts/asm-installer/tests/run_cli_tests
Bugfixes, compatibility, and version bump
=> Staging 1.8 asm

asm/vm/asm_vm
=> Do not exclude startup-script in metadata

asm/vm/asm_vm
=> [VM Script] Add default istiod service name resolution

scripts/asm-installer/install_asm
Resolve: https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/issues/469
=> Use client side apply for CRD installation of MCP

asm/vm/README.md, scripts/asm-installer/README.md, scripts/asm-installer/asm_vm, scripts/asm-installer/cloudbuild-flaky.yaml, scripts/asm-installer/cloudbuild-master.yaml, scripts/asm-installer/release_asm_installer, scripts/asm-installer/tests/common.sh
- move `asm_vm` to asm-installer folder.
- add `asm_vm` to the release script.
- create initial README of the `asm_vm` script.
=> Move asm_vm script

asm/istio/istio-operator.yaml, scripts/asm-installer/install_asm, scripts/asm-installer/tests/common.sh, scripts/asm-installer/tests/fake_gcloud, scripts/asm-installer/tests/fake_kubectl, scripts/asm-installer/tests/run_basic_suite_managed, scripts/asm-installer/tests/run_cli_tests, scripts/asm-installer/tests/setup_longterm_cluster
* Do not block validation on asmv label (#454)
* Add BSD csplit compatibility (#449)
* Conditionally require APIs for CA (#442)
* Conditionally require APIs for CA
* Enable specifying alpha builds for testing (#417)
* Use less privileged operations during validation (#418)
* Bump point version
=> Merge Staging 1.8 asm to release-1.8-asm (#465)

asm/Kptfile, asm/istio/expansion/expose-istiod.yaml
Update based on https://github.com/istio/istio/blob/master/samples/multicluster/expose-istiod.yaml to use TLS routing for correct revision selection.
/cc @nmittler
=> Update istiod routing config

scripts/asm-installer/cloudbuild-flaky.yaml, scripts/asm-installer/cloudbuild-master.yaml
This has been passing consistently after the staging issues were worked out
=> Move MCP test back to normal config

scripts/asm-installer/install_asm, scripts/asm-installer/tests/run_cli_tests
=> Improve node pool validation

asm/istio/options/vm.yaml, scripts/asm-installer/tests/common.sh
RC was membership was accidentally deleted. Membership enablement is fixed.
This PR fixes unknown commands in test.
=> Fix failing VM test

scripts/asm-installer/cloudbuild-flaky.yaml, scripts/asm-installer/cloudbuild-master.yaml
The past few runs of VM tests did not fail, so moving the tests back to master pipeline.
=> Move vm test to master test job

scripts/asm-installer/asm_vm
Manually verified the updated default agent is working.
=> Update default service proxy agent address

scripts/asm-installer/install_asm
Avoid GKE WP validation error when Environ WP is being used.
=> Add GKE WP enablement condition for unmanaged ASM

scripts/asm-installer/install_asm
=> Add BSD csplit compatibility (#449)

scripts/asm-installer/asm_vm
=> use fetched cluster id in meta

asm/Kptfile, scripts/asm-installer/install_asm
Couple of bugfixes and a default value fix
=> Release 1.8 asm

asm/Kptfile, asm/istio/istio-operator.yaml
As we discuss I am copying the full thing from the release to our branch.
=> Anthos sample deployment

scripts/asm-installer/install_asm
Related to #476. The release script part is going to require a refactor so I'm splitting it into a different PR.
=> Add proper SemVer support

scripts/asm-installer/install_asm
Tested all three cases manually.
=> Don't overwrite configuration from a different version

scripts/asm-installer/release_asm_installer
In preparation for adding version check logic. Behavior unchanged, tested manually.
=> Refactor release script

scripts/asm-installer/asm_vm, scripts/asm-installer/tests/common.sh
=> VM script should fail when service accounts mismatch

scripts/asm-installer/asm_vm, scripts/asm-installer/release_asm_installer
=> Check tags when releasing install_asm

scripts/asm-installer/install_asm
Add region tags around required_iam_roles so I can display the roles in a docwidget.
=> Add region tags around required_iam_roles

scripts/migration/README.md, scripts/migration/upgrade-14-16, scripts/migration/upgrade-14-16.sh
Script for automating some of the steps described in the [addon upgrade docs](https://cloud.google.com/istio/docs/istio-on-gke/upgrade-with-operator).
=> Istio GKE addon 1.4 to 1.6 migration script

asm/Kptfile, asm/istio/options/revisioned-custom-ingressgateway.yaml, asm/istio/options/revisioned-istio-ingressgateway.yaml, scripts/asm-installer/install_asm
cherry-pick #544 from staging to release
=> Staging 1.7 asm

scripts/asm-installer/install_asm
* Change how to retrieve environ project id
=> Change how to retrieve environ project id (#571)

scripts/asm-installer/release_asm_installer
Update to publish the files with name specified [here](https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/master/docs/versioning.md#tldr). Addressing issue #476
=> publish the file name as SemVer

scripts/asm-installer/install_asm, scripts/asm-installer/tests/common.sh, scripts/asm-installer/tests/run_basic_suite_required_roles, scripts/asm-installer/tests/setup_longterm_cluster
Bind roles only when the --enable-* flags are passed in by the user.  The test currently runs manually. Automation will come in separate PRs.
=> Conditional required roles

scripts/asm-installer/install_asm, scripts/asm-installer/tests/common.sh, scripts/asm-installer/tests/fake_kubectl
Fixed a bug that the `istio-namespace` will be created during validation. Also added a flag so that the user could choose to have this namespace created for them.
=> added the flag to create the namespace

scripts/asm-installer/install_asm
Actually apply the validating webhook instead of only directing the users to do it.
=> apply the validating webhook

scripts/asm-installer/tests/common.sh, scripts/asm-installer/tests/setup_longterm_cluster
add function to remove duplicate image instances and template
=> add function to remove duplicate image instances and template

scripts/asm-installer/README.md, scripts/release-asm/README.md
Add readme for the new release.
=> update the readme for release

scripts/asm-installer/install_asm
=> Fix namespace validation in 1.9

BUILD, asmcli/asmcli.sh, asmcli/lib/context.sh, asmcli/tests/lib/context.bats
This split the argument parsing and validation to `asmcli/lib/parse.sh`. We interact with the `CONTEXT_JSON` variable in parse and validation just to avoid unnecessary I/O. After arguments are validated, we dump the json to the local workspace in `set_up_local_workspace`.
This changes the behavior of accessing and writing global variables. The source of truth for the arguments will be in the `CONTEXT_JSON` file. All variables will read this file first.
=> refactor args parsing and validation

asm/Kptfile, asm/istio/options/cni-managed.yaml
Generated CNI yaml for the k8s objects and a Kpt setter for the image
=> Add config for MCP CNI

asmcli/lib/context.sh, asmcli/tests/lib/context.bats
this PR adds the implementation for the yaml files appending and unit tests.
=> append the yaml and add unit tests

asmcli/asmcli.sh, asmcli/commands/install.sh, asmcli/components/ca/citadel.sh, asmcli/components/ca/mesh-ca.sh, asmcli/components/ca/private-ca.sh, asmcli/components/control-plane/managed.sh
This PR refactors the configure steps to take place in install subcommand and in each individual components.
=> refactor configure

asm/Kptfile, asm/istio/options/hub-meshca.yaml, scripts/asm-installer/asm_vm
Reverts GoogleCloudPlatform/anthos-service-mesh-packages#678
=> Revert "[1.10 Only] Update hub workload pool suffix"

asmcli/asmcli.sh, asmcli/commands/install.sh, asmcli/commands/validate.sh, asmcli/components/ca/citadel.sh, asmcli/components/ca/private-ca.sh, asmcli/components/control-plane/in-cluster.sh, asmcli/components/control-plane/managed.sh
first PR to refactor validation.
=> refactor validation

scripts/asm-installer/install_asm, scripts/asm-installer/tests/common.sh
This is a port of @backward-compatible's work on the v2 branch to allow a few specific users to use this feature undocumented and unblock use cases.
=> Kc oldtaro

asm/Kptfile, asm/istio/options/hub-meshca.yaml
Reverts GoogleCloudPlatform/anthos-service-mesh-packages#694
=> Revert "[1.10 Only] Use new Hub WP and update GKE_CLUSTER_URL"

scripts/asm-installer/cloudbuild-master.yaml
Will need to update the cloud build variable substitution in the UI as well.
=> Allow testing ASM package change in the same PR

asm/Kptfile, asm/istio/options/hub-meshca.yaml, scripts/asm-installer/asm_vm, scripts/asm-installer/install_asm
This PR includes https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/694.
Roll forward https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/678 with some fixes to GKE_CLUSTER_URL
=> [1.10 Only] Use new Hub workload pool

asmcli/asmcli.sh, asmcli/commands/install.sh, asmcli/commands/print-config.sh, asmcli/commands/validate.sh, asmcli/lib/context.sh
This PR manually ensures all global variables are read only and all other variables are local and use context interfaces.
=> remove global references

scripts/asm-installer/asm_vm
To be consistent with https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/master/scripts/asm-installer/install_asm#L1601
=> asm_vm: prepend project id to network id

scripts/ca-migration/README.md, scripts/ca-migration/migrate_ca
Cherry-pick https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/554 into 1.10.
=> Add CA migration script.

asm/control-plane-revision/cr_rapid.yaml, asm/control-plane-revision/cr_regular.yaml, asm/control-plane-revision/cr_stable.yaml, asm/control-plane-revision/crd.yaml, asmcli/asmcli, asmcli/asmcli.sh, asmcli/commands/install.sh
I had to do a lot of manual conflict resolution so review it like new code please :)
=> add crd/cr files for cpr and apply them (#739)

asm/Kptfile, scripts/asm-installer/asm_vm, scripts/asm-installer/cloudbuild-master.yaml, scripts/asm-installer/install_asm, scripts/asm-installer/tests/setup_longterm_cluster
* Require Fleet registration with MCP
* Bump rev
* Small refactor for readability
=> Require Fleet registration with MCP

asmcli/asmcli, asmcli/asmcli.sh, asmcli/cloudbuild-main.yaml, asmcli/commands/help.sh, asmcli/commands/validate.sh, asmcli/components/control-plane/in-cluster.sh, asmcli/tests/main_test.bats, asmcli/tests/run_basic_suite_managed_vm
The requirements are:
- Cluster should be registered to a fleet
- GCE IdentityProvider should be registered
- Service mesh feature should be enabled
=> Allow VM setup for MCP

asmcli/asmcli, asmcli/asmcli.sh, asmcli/commands/experimental.sh, asmcli/commands/experimental/help.sh, asmcli/tests/lint_variables
Also adds a fix to the variable lint to skip if it doesn't find any.
=> Add experimental subcommand

asmcli/asmcli, asmcli/asmcli.sh, asmcli/tests/main_test.bats
=> Check platform for kpt better

asm/istio/options/cni-managed.yaml
cc @mandarjog @ostromart @therealmitchconnors
=> Add MDP controller to asmcli.

asm/Kptfile, asm/istio/options/cni-managed.yaml
Cherry-pick https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/794 and #800  to master branch for install-asm based install.
=> Add MDP controller to asmcli. (#794)

asm/istio/options/cni-managed.yaml
This is the manifest from istio master. We will migrate AFC install so this probably will never be shipped with ASM 1.11. Mostly this is to make prow test happy.
cc @richardwxn @ruigulala
=> Bring in the latest istio cni manfiest.

asm/Kptfile, asm/istio/options/cni-managed.yaml
* Add MDP controller to asmcli. (#794)
* Separate MDP and CNI image substituion. (#800)
=> Add MDP controller to asmcli. (#794) (#799)

asmcli/asmcli, asmcli/asmcli.sh
Unquote the command so that it is not treated as a file to run.
=> Fix registration

asm/istio/options/cni-managed.yaml
Made a mistake in #804 and accidently bring in istio master CNI manifest. This PR reverts that commit back at 1.10 staging.
=> Revert "Bring in the latest istio cni manfiest."

asm/istio/options/private-ca.yaml
=> Amending Private CA Istio Operator option

asm/Kptfile, asm/istio/istio-operator.yaml, asm/istio/options/citadel-ca.yaml, asm/istio/options/off-gcp.yaml, asmcli/asmcli, asmcli/lib/config.sh
kpt doesn't merge the maps, so we should set all of the env variable for pilot explicitly
=> Set env variables explicitly

scripts/asm-installer/asm_vm
Manual cherrypick of https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/774
Tested locally with kpt 1.0.0 installed by default.
=> Download kpt when necessary for asm_vm

asmcli/asmcli, asmcli/commands/validate.sh, asmcli/lib/checks.sh, asmcli/lib/context.sh, asmcli/lib/util.sh, asmcli/lib/validate.sh, asmcli/tests/lib/context.bats, asmcli/tests/lib/util.bats, asmcli/tests/main_test.bats
=> only-validate will not exit

asm/identity-provider/identityprovider-crd.yaml, asmcli/.yamllint
* Update IDP CRD to v1
* newline
* update yamllint config
=> Update IDP CRD to v1 (#860)

asm/istio/options/cni-managed.yaml
Cherry-pick of https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/863
=> [staging 1.10] Update MDP CRD to v1

scripts/vsphere/README.md, scripts/vsphere/attach_vm, scripts/vsphere/runagent.sh, scripts/vsphere/stopagent.sh, scripts/vsphere/util.sh
This PR includes following changes:
1.  Support attaching Debian VM 
2.  Delete script dependency to gcloud and projectID
3.  Support Auto get meshID from IstioOperator
4. Support attaching VM to istiod with revision label
5. Support checking of workloadentry generation after attaching a VM
=> Add deb VM support for attachable VM

asm/control-plane-revision/cr_rapid.yaml, asm/control-plane-revision/cr_regular.yaml, asm/control-plane-revision/cr_stable.yaml
cherry-pick remove dataplane (#748)
=> Staging 1.10 asm

scripts/asm-installer/install_asm
Change IAM member format for integration with CAS
=> CAS: Change IAM member format

asm/istio/options/cni-gke-autopilot.yaml
Cherry-pick https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/930
=> Fix CNI Autopilot overlay. 

asm/istio/options/cni-gke-autopilot.yaml
Apparently I should have done some verification on the manifest checked in at #922
=> Fix CNI Autopilot overlay.

asmcli/asmcli, asmcli/lib/util.sh, asmcli/lib/validate.sh
install with `install_asm`
```
./install_asm --mode install -p zhengzhe-anthos-test -n test-cluster-1 -l us-central1-c
...
install_asm: *****************************
install_asm: Successfully installed ASM.
k get deployments -n istio-system                                                                
NAME                   READY   UP-TO-DATE   AVAILABLE   AGE
istio-ingressgateway   2/2     2            2           43s
istiod-asm-1104-6      2/2     2            2           6d19h
```
install with `asmcli` and choose to stop
```
2021-09-02T19:38:18.597013 asmcli: -------------
2021-09-02T19:38:19.083556 asmcli: [WARNING]: Defaults have changed between previous installation methods and this tool.
2021-09-02T19:38:19.149263 asmcli: [WARNING]: We detected an ASM ingress gateway currently …
```
=> warn user if they are upgrading with the default ingress gateway

scripts/asm-installer/install_asm, scripts/asm-installer/tests/run_basic_suite_managed
Similar change as https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/937. Not sure if this is needed for install_asm though..
=> Make CNI always on at managed ASM.

asm/istio/options/cni-managed.yaml
AFC based installation is not ready yet. Update manifest to the 1.11 which is the same as master branch: https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/master/asm/istio/options/cni-managed.yaml
=> Update managed CNI manifest at asmcli.

asmcli/asmcli, asmcli/commands/install.sh
Derive Project ID from CA_NAME in case ca pool is setup in a different project
=> CAS: Fixing Project ID

scripts/asm-installer/install_asm
Fixing where we get project ID from
=> masterCas master project

scripts/asm-installer/Dockerfile, scripts/asm-installer/install_asm, scripts/asm-installer/tests/run_cli_tests
Cherry-pick of #774 with conflicts manually resolved.
=> Download kpt when necessary (#774)

asm/canonical-service/controller.yaml, asm/istio/options/managed-control-plane-webhooks.yaml
Manual cherry pick of https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/1007 onto master.
=> [master] Update resources to use v1 for k8s 1.22

scripts/migration/migrate-addon
=> Update migrate-addon script

asm/istio/options/distroless-proxy.yaml
Sorry, I missed the file extension
=> Rename distroless-proxy to distroless-proxy.yaml

scripts/asm-installer/install_asm
https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/commit/3003df876a630862da89ce19abcd56d81f62a532 updated it for `asmcli`, this PR is for `install_asm`.
=> Update kubectl command for install_asm

asmcli/asmcli, asmcli/lib/installation_dependencies.sh
=> Include meshconfig in required_fleet_apis

asmcli/asmcli, asmcli/commands/install.sh
Increase logging and retries to debug tests
=> privateca: temporarily enhance debuggability

asmcli/asmcli, asmcli/commands/help.sh, asmcli/commands/install.sh, asmcli/components/ca/private-ca.sh
Add certificate template support by appending the CT to the --ca_pool param.
=> add certificate template support for google-cas installation

asmcli/asmcli, asmcli/commands/install.sh
revert privateca IAM binding debug log and reduce retry time
=> revert privateca debug log

asmcli/asmcli, asmcli/lib/checks.sh, asmcli/lib/validate.sh
Update gcloud commands in asmcli:
* Use gcloud GA version instead of beta
* Use gcloud container fleet instead of gcloud container hub
=> update gcloud command

asmcli/asmcli, asmcli/lib/context.sh, asmcli/lib/installation_dependencies.sh
Added an extra parameter while creating membership for openshift cluster.
=> updated fleet registration for openshift clusters

asm/istio/options/attached-cluster.yaml
Ensures that Control plane certificate is self signed.
Option file only for in-cluster installations, not for MCP
=> ASM EKS/AKS In-cluster: essential option file

asm/istio/options/prometheus-and-stackdriver.yaml, asm/istio/options/stackdriver.yaml
These tags let only the yaml appear in the ASM docs
=> Adds docs tags

asm/istio/options/managed_cas.yaml
Add an Istio operator config file for managed CAS to support the installation with managed CAS.
=> Add Istio operator config file for managed CAS

asmcli/asmcli, asmcli/components/ca/managed-cas.sh
Add a function for enabling the workload certificate API.
=> Add a function for enabling the workload certificate API

asmcli/asmcli, asmcli/components/ca/managed-cas.sh
Enable workload certificate feature on the fleet.
=> Enable workload certificate feature on the fleet

asmcli/asmcli, asmcli/components/ca/managed-cas.sh
Enable workload certificate feature on a membership.
=> Enable workload certificate feature on a membership

asmcli/asmcli, asmcli/components/ca/managed-cas.sh, asmcli/components/control-plane/managed.sh
Configure managed CAS for MCP.
=> Configure managed CAS for MCP

scripts/migration/ca-migration/migrate_ca
=> Additional changes

asmcli/asmcli, asmcli/commands/install.sh, asmcli/commands/validate.sh, asmcli/lib/validate.sh
Validate the dependencies for managed CAS.
=> Validate the dependencies for managed CAS

asmcli/asmcli, asmcli/components/ca/managed-cas.sh, asmcli/lib/installation_dependencies.sh
Enable the workload certificate API.
=> Enable the workload certificate API

asmcli/asmcli, asmcli/lib/checks.sh, asmcli/lib/validate.sh
Validate CA consistency for managed CAS.
=> Validate CA consistency for managed CAS

asmcli/asmcli, asmcli/lib/validate.sh
Update the error message for managed CAS.
=> Update the error message for managed CAS

asmcli/asmcli, asmcli/lib/installation_dependencies.sh
Turns out we already had this somewhere except as a different name.
=> Reconcile option names

asmcli/asmcli, asmcli/commands/help.sh
Comment ca=managed_cas is experimental
=> Comment ca=managed_cas is experimental

asmcli/asmcli, asmcli/components/ca/managed-cas.sh, asmcli/lib/installation_dependencies.sh, asmcli/lib/validate.sh
Reconcile the managed certificate code with the code tested in the bug bash.
=> Reconcile the managed certificate code with the code tested

asmcli/asmcli, asmcli/components/ca/managed-cas.sh, asmcli/lib/installation_dependencies.sh, asmcli/lib/validate.sh
Reconcile the managed certificate code with the tested code [cherrypick PR 1281]
=> Reconcile the managed certificate code with the tested code [cherrypick PR 1281]

asmcli/asmcli, asmcli/components/ca/managed-cas.sh
Add retry to workload cert enablement.
=> Add retry to workload cert enablement

asmcli/asmcli, asmcli/components/ca/managed-cas.sh
Add retry to workload cert enablement [cherry-pick #1283]
=> Add retry to workload cert enablement [cherry-pick #1283]

asmcli/asmcli, asmcli/lib/installation_dependencies.sh
Kicking off release tests for #1294
=> Reconcile option names (#1260)

asm/istio/options/envoy-core-dump.yaml
https://b.corp.google.com/issues/215552264
=> add core dump

asm/Kptfile, asmcli/asmcli, asmcli/asmcli.sh
=> Bump rev 1.15.3-asm.1 (#1349)

asmcli/asmcli, asmcli/lib/context.sh
Give a potential action item in case this is unexpected behavior.
=> Be more explicit in logs around env vars.

asmcli/asmcli, asmcli/lib/validate.sh
=> Fixing error message (#1396)

asmcli/README.md, asmcli/asmcli, asmcli/commands/build-offline-package.sh, asmcli/commands/create-mesh.sh, asmcli/lib/parse.sh, asmcli/tests/common.sh, scripts/migration/ca-migration/migrate_ca
Add `working_dir` alias for OUTPUT_DIR context variable.
=> Add --working-dir alias for output directory

asm/istio/istio-operator.yaml
=> cleanup: remove dead env var

asmcli/asmcli, asmcli/lib/config.sh, asmcli/lib/util.sh
This reverts commit ea6dd07d43093888089739a3409a51318c54cab5.
This commit is not ready to be merged to main branch yet.
=> Revert "Populate MonitoringConfig values to GCP_METADATA (#1498)"

asmcli/asmcli, asmcli/lib/config.sh, asmcli/lib/util.sh
Populate CLUSTER_NAME, PROJECT_ID, and CLUSTER_LOCATION for GCP_METADATA env variable from fleet monitoring config.
=> Populate MonitoringConfig values to GCP_METADATA

asmcli/asmcli, asmcli/lib/config.sh, asmcli/lib/util.sh
* Populate MonitoringConfig values to GCP_METADATA (#1498)
* Populate MonitoringConfig values to GCP_METADATA
* Add quotes to fix build lint error
* Add quotes to fix build lint error
* Resolve minor problem and code optimization
* Add double-quotes for lint
* Update lint changes
=> Populate MonitoringConfig values to GCP_METADATA (#1511)

asmcli/asmcli, asmcli/lib/config.sh, asmcli/lib/util.sh
This reverts commit 73ff3b307500728cbc0eff687f774941181c2586.
=> Revert "Populate MonitoringConfig values to GCP_METADATA (#1511)" and "Update the logic to identify empty monitoring config (#1516)"

asm/istio/istio-operator.yaml
Patch for https://github.com/istio/istio/pull/47892
=> Drop legacy telemetry install

asm/Kptfile, asmcli/asmcli, asmcli/asmcli.sh
* Bump revision 1.20.2-asm.0 (#1559)
* Drop legacy telemetry isntall (#1566)
* rename rhel cni (#1567)
* Bump revision 1.20.3-asm.5 (#1569)
* Bump revision 1.20.3-asm.5
* Update google-cloud packages
* Update revision 1.20.3-asm.4 (#1579)
---------
=> Merge main to staging-1.20 (#1583)

asm/Kptfile, asmcli/asmcli, asmcli/asmcli.sh
Add latest Point and Rev in asmcli staging-1.23 for latest istioctl binary
=> Add latest Point and Rev in asmcli staging-1.23 for latest istioctl

asm/istio/options/cni-baremetal-rhel.yaml
Adding this for fixing the ongoing cni daemonset failing issue, due to privilege being set to false in securityContext
=> Update cni-baremetal-rhel.yaml add spc_t seLinuxOption

asm/Kptfile, asmcli/asmcli, asmcli/asmcli.sh
* Update Kptfile
* Update asmcli
* Update asmcli.sh
=> Bump rev 1.22.8-asm.5 (#1682)

asm/Kptfile, asmcli/asmcli, asmcli/asmcli.sh
* Update Kptfile
* Update asmcli
* Update asmcli.sh
=> Bump rev 1.23.5-asm.3 (#1683)

asm/Kptfile, asmcli/asmcli, asmcli/asmcli.sh
* Update Kptfile
* Update asmcli
* Update asmcli.sh
=> Bump rev 1.24.3-asm.6 (#1684)

asm/Kptfile, asmcli/asmcli, asmcli/asmcli.sh
* Bump asm rev to 1.26.0-asm.8 (#1717)
* bump rev to 1.26.0-asm.11 (#1719)
=> Bump asm rev to 1.26.0-asm.11 (#1717) (#1718)

asm/Kptfile, asmcli/asmcli, asmcli/asmcli.sh
Bump asmcli version to latest 1.26.4-asm.1
=> Bump asmcli version to latest 1.26.4-asm.1

asm/Kptfile, asmcli/asmcli, asmcli/asmcli.sh
Bump asmcli version to latest 1.26.4-asm.1
=> Bump asmcli version to latest 1.26.4-asm.1 

asm/Kptfile, asmcli/asmcli, asmcli/asmcli.sh
- **Bump rev 1.24.6-asm.4**
- **Bump Rev 1.24.6-asm.9 (#1726)**
- **Bump Rev bump-1.24.7-asm.0 (#1732)**
=> Bump Rev bump-1.24.7-asm.0
