GoogleCloudPlatform/anthos-service-mesh-packages

- asm/cluster/cluster.yaml
A user may not be using the default VPC network or subnetwork.  Allowing `kpt` to change these values would be convenient.
> Adding kpt annotations for network and subnetwork

- kustomize-functions/validate-asm/image/main.go
It includes the following changes:
- Ignore kpt annotations in the node value field
- Remove validation on the master node version as the new requirement only requires using a release channel, but no specific master node versions
- Validate containerCluster's machineType only when it exists
- Make the validator understand both nodeCount and initialNodeCount
- Support Warning level validation errors
> Update the kpt validation function

- README.md
- asm/Kptfile
- asm/cluster-td/neg-controller-default-backend.yaml
- asm/cluster-td/neg-controller-rbac.yaml
- asm/cluster-td/neg-controller.yaml
- asm/infrastructure_configs.sh
- asm/trafficdirector/crd-all.gen.yaml
- asm/trafficdirector/neg-controller-config.yaml
- asm/trafficdirector/td-configmap-galley.yaml
- asm/trafficdirector/td-configmap-injection.yaml
- asm/trafficdirector/td-configmap-mesh.yaml
- asm/trafficdirector/td-galley-rbac.yaml
- asm/trafficdirector/td-galley.yaml
- asm/trafficdirector/td-gateway.yaml
- asm/trafficdirector/td-istiod-asm-rbac.yaml
- asm/trafficdirector/td-istiod-asm.yaml
- asm/trafficdirector/td-mutatingwebhook.yaml
- cluster/Kptfile
- cluster/cluster/cluster.yaml
- project/Kptfile
- project/project/enable-services.yaml
- project/project/force-p4sa-generation.yaml
- project/project/neg-sa.yaml
- project/project/td-galley-sa.yaml
Updating ASM Managed Control Plane branch to support AnthosCLI beta.
Also changed the Galley config to no longer require a serviceaccount key, and added an ASM gateway deployment.
> Updating ASM Managed Control Plane branch to support anthoscli beta

- asm-patch/Kptfile
- asm-patch/resources/istio-operator.yaml
- asm/Kptfile
- asm/cluster/istio-operator.yaml
This allows any cluster & ASM installation created with this package to
participate in a multicluster mesh when used with the multicluster
install guide.
> Update packages for 1.6 to include multicluster attributes.

- asm-patch/resources/istio-operator.yaml
- asm/cluster/istio-operator.yaml
Enable Stackdriver Tracing by default and add custom tags  for canonical service and revision
> Enable Stackdriver Tracing by default

- asm-patch/resources/istio-operator.yaml
- asm/cluster/istio-operator.yaml
Reverts GoogleCloudPlatform/anthos-service-mesh-packages#78
This broke multicluster tests.
> Revert "Enable Stackdriver Tracing by default"

- asm/Kptfile
- asm/cluster/istio-operator.yaml
Instructions in docs reference 1.5.6-asm.0, but 1.5.5-asm.2 is pulled.
Instructions for upgrades in docs has users pulling `istio-1.5.6-asm.0-linux.tar.gz`, which `istioctl` conflicts with our packaged manifests.
> Rev asm version to 1.5.6-asm.0

- asm-citadel/cluster/istio-operator.yaml
- asm-patch-citadel/resources/istio-operator.yaml
- asm-patch/resources/istio-operator.yaml
- asm/cluster/istio-operator.yaml
People started to use anthoscli to install ASM using this latest control plane monitoring enablement option and build that is not yet ready (<=1.6.8-asm.0). Will add this option back when the next patch version is ready.
> disable control plane monitoring in 1.6 for now

- asm-citadel/Kptfile
- asm-citadel/canonical-service/controller.yaml
- asm-patch-citadel/Kptfile
- asm-patch-citadel/resources/canonical-service/controller.yaml
- asm-patch/Kptfile
- asm-patch/resources/canonical-service/controller.yaml
- asm/Kptfile
- asm/canonical-service/controller.yaml
Now that canonical-service-controller has been added to gke-release, I'm updating the URLs to point to the final location and version number.
> update gke-release image url

- asm-citadel/Kptfile
- asm-patch-citadel/Kptfile
- asm-patch-citadel/resources/kustomization.yaml
- asm-patch/Kptfile
- asm/Kptfile
Fix the issue where GCP_METADATA is not set properly when environ Id != project Id.
But this will introduce one more step for the current asm-gcp installation, i.e. we will need to set
kpt cfg set gcloud.project.environProjectNumber <envrion project number>
> Fix gcp metadata

- asm-citadel/cluster/istio-operator.yaml
- asm-patch-citadel/resources/istio-operator.yaml
- asm-patch/resources/istio-operator.yaml
- asm/cluster/istio-operator.yaml
Reverts GoogleCloudPlatform/anthos-service-mesh-packages#116
Brings back control plane monitoring, since current image has this function ready.
> Revert "disable control plane monitoring in 1.6 for now"

- asm-patch/Kptfile
- asm-patch/canonical-service/controller.yaml
- asm-patch/resources/kustomization.yaml
- asm/Kptfile
- asm/canonical-service/controller.yaml
These are the same changes we added to the 1.6 branch, simplified for 1.7.
The content of the two controller.yaml files are identical.
I will follow up with a similar PR adding these changes to master so that we don't have to "forward port" this for the next release.
> add canonical-service to 1.7

- asm-patch/Kptfile
- asm/Kptfile
- asm/istio/options/hub-meshca.yaml
- pkg/Kptfile
- pkg/istio/options/hub-meshca.yaml
This adds an option for `ASM + Hub IDNS + MeshCA` installation. 
- It adds an option file `hub-meshca.yaml` for Hub IDNS + MeshCA.
- It adds extra setters and substitutions specifically for Hub IDNS. No original setters or substitutions are changed except trustDomainAlias to support Hub pattern.
- It does not enable stackdriver currently as stackdriver does not support Hub IDNS. 
```
gcloud config set project ${PROJECT_ID}
kpt pkg get https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages.git/asm@master asm
kpt cfg set asm gcloud.project.environProjectID ${ENVIRON_PROJECT_ID}
kpt cfg set asm anthos.servicemesh.hubMembershipID ${HUB_MEMBERSHIP_ID}
istioctl install -f asm/istio/istio-operator.yaml -f asm/istio/options/hub-meshca.yaml
```
```
gcloud config set project …
```
> Add option for Hub IDNS with MeshCA in GCP

- scripts/asm-installer/install_asm
Previously the script would exit with a non-zero error code, but not printing the message.
> Fix to Anthos Service Mesh install script so that multi-line error message are printed.

- scripts/asm-installer/install_asm
- scripts/asm-installer/tests/fake_gcloud
We now require >= 8 vCPUs in node pools whose machine size is >= 4 vCPUs.
(So this changes the structure of the requirement.)
> Updated minimum resource requirements for script install

- scripts/asm-installer/install_asm
I did this specifically because without this change if you type `./install_asm` with no args, it doesn't report usage, but just complains about needing mode to be install or migrate.
> Report missing args with higher priority that wrong arg values

- scripts/asm-installer/install_asm
* Remove (optional) tag since there is no reasonable way to be
consistent between different types of conditionally optional options
* Remove spacing between option types
* Separate flags from options
* Add a period to all descriptions
* Move allowed values to the end of descriptions
* Standardize descriptions for optional options on "This can be omitted
if..."
* Language tweaks for parallelism
> Make usage prompt more consistent

- scripts/asm-installer/install_asm
* Pull file-related constants to the top
* Download kpt configuration earlier in the process
* Fix bug in checking for operator overlay (-f -> -n)
* Add option to specify directory
* Re-use files if they exist in specified directory
* Misc cleanup of unnecessary validation
> Add --output_dir option to specify location to download packages

- scripts/asm-installer/install_asm
Parameterize version, image, and package location to allow customization of CI pipelines
Allow passing credentials when downloading ASM package to allow SAs access
Minor refactorings to support the above
> Allow flexibility in ASM version for testing

- scripts/asm-installer/install_asm
- scripts/asm-installer/tests/run_cli_tests
* Allow passing multiple -o options to specify multiple yaml files
* Refactor citadel option to just add the file into the overlays instead of special casing it
* Changed CLI tests to use meshca since validation changed location in the script
> Allow multiple operator overlays

- scripts/asm-installer/install_asm
Also fix a bug where an error would fail to print if a machine type that didn't end in a number was in a node pool.
> Fail earlier if kubectl can't connect

- scripts/asm-installer/install_asm
Turns out gcloud only looks at one of the --role flags.
> Fix iam bindings

- scripts/asm-installer/install_asm
Instead of installing anything, just print the config that would have been applied. This also skips verification and cluster/project setup. Closes #169.
Sample output (citadel was chosen to include an additional yaml file to overlay):
```
$>install_asm -l us-central1-c -n basic-suite-981hztoe -p test-cluster -m install -c citadel --print-config > testfile
$>cat testfile
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
profile: asm-gcp
hub: gcr.io/asm-staging-images/asm
tag: 1.7.1-asm.0
components:
pilot:
k8s:
env:
- name: SPIFFE_BUNDLE_ENDPOINTS
value: "test-cluster.svc.id.goog|https://storage.googleapis.com/mesh-ca-resources/spiffe_bundle.json"
- name: ENABLE_STACKDRIVER_MONITORING
value: "true"
meshConfig:
defaultConfig:
proxyMetadata:
GCE_METADATA_HOST: …
```
> Add --print-config flag

- scripts/asm-installer/install_asm
- scripts/asm-installer/tests/fake_gcloud
* Bump image version for staging tests
* The validation fails if there is more than one node pool, this fixes it so that if the max CPU pool is valid then we pass
> Fix node pool validation

- scripts/asm-installer/install_asm
Generally the stderr for commands isn't useful. Silence it by default, and make the --verbose output more readable.
> Reduce noise when installing

- scripts/asm-installer/install_asm
Since we go through the trouble of generating configuration, we might as well save it. If the user ever needs to roll back or reference it they'll have it on hand.
* Refactor redirection to happen outside of print_config
* Remove cleanup_local_workspace since there's not much point now that we're leaving a lot there anyways
* Also, refactor out success because of above
* Add the canonical service yaml to print_config
* Save the raw DRY config along with the expanded config from istioctl manifest generate to the working directory
* Update outro to print the locations of these
> Save configuration after running istioctl

- scripts/asm-installer/install_asm
The current usage prompt is taller than my full-screen terminal. This defaults to a shorter usage prompt that doesn't have descriptions, and adds the descriptions if you use help with the verbose flag. It also handles the case where no arguments are passed better--it used to complain about missing required arguments, now it just lists the usage (which is the standard).
> Add shorter usage

- scripts/asm-installer/Dockerfile
- scripts/asm-installer/cloudbuild.yaml
- scripts/asm-installer/install_asm
- scripts/asm-installer/tests/common.sh
- scripts/asm-installer/tests/run_install_custom_cert_suite
* Add 4 long options to install_asm for custom certificate files
* Validates openssl CLI dependency if installing a custom cert
* Validate files exist, and passing any option requires passing all of them
* Validate that cusom ca arguments only work with citadel
* Validate formats of root/CA/key
* Validate key matches CA cert 
* Validate that chain of trust is valid for root -> CA
* Creates the cacerts k8s secret from given files
* Added e2e test that generates certs, installs with them, them verifies the ones from istio-proxy are the same as the ones generated
* Added e2e test to cloudbuild
> Support custom certificates for Citadel

- kustomize-functions/validate-asm/image/main.go
The current validate function checks each individual nodepool separately. We need to update the function to check the aggregated vcpu counts from multiple nodepools.
It also downgrades the machineType check failure from Error to Warning.
Fixes #66.
> Aggregate vCPU count for all nodepools

- kustomize-functions/validate-asm/image/main.go
It cherry-picks the changes of the validate-asm function from the `master` branch.
The current validate function checks each individual nodepool separately. We need to update the function to check the aggregated vcpu counts from multiple nodepools.
> Aggregate vCPU count for all nodepools (#192)

- asm-iap/Kptfile
- asm-iap/cluster/istio-operator.yaml
This will allow users to upgrade with continuity.
Note: this doesn't currently work and I don't know why.  Running any kpt command results in the following:
`error: json: cannot unmarshal number into Go struct field setter.setter.value of type string`
> allow explicitly overriding http and status nodeports

- scripts/asm-installer/cloudbuild.yaml
- scripts/asm-installer/install_asm
- scripts/asm-installer/tests/common.sh
- scripts/asm-installer/tests/run_migration_suite_citadel_prev
- scripts/asm-installer/tests/run_migration_suite_meshca_prev
Relax the version validation a bit and add end to end tests for migration from the previous minor version of Istio.
> Add tests for migration from previous version

- scripts/asm-installer/install_asm
This works accidentally if you're close enough to US datacenters, but otherwise enabling MeshCA will fail because workload identity isn't created.
> Reorder workload identity and MeshCA init

- asm-iap/Kptfile
- asm-iap/istiod-service.yaml
This should have been in the original commit to the 1.6 release branch, and I just accidentally left it out.
> Add validating webhook fix to asm-iap

- asm/Kptfile
- asm/istio/options/iap-operator.yaml
Moving around a cherry-pick of #222 onto master
> allow explicitly overriding http and status nodeports (#222)

- pkg/istio/options/hub-meshca.yaml
With GKE_CLUSTER_URL exported to pilot, ENABLE_STACKDRIVER_MONITORING can be enabled, which has been tested.
> export GKE_CLUSTER_URL to pilot for Hub overlay

- scripts/asm-installer/install_asm
Style fixes:
* return 1 -> false
* standardized checking using -eq everywhere possible
* removed excess semicolons
Readability:
* moved common condition checks into functions
* pulled out a lot of modifications and validations, to make it clearer what `main` is doing and also to prepare for splitting things up for #207
> Style fixes and readability

- scripts/asm-installer/install_asm
Fixes #260 
If a policy already has conditions, you must set the condition option even if there aren't any conditions.
> Explicitly set no condition when binding IAM roles

- scripts/asm-installer/install_asm
Cherry pick of three bugfixes:
* use `stat` instead of `readlink` on Mac
* fix the cluster label delimiter
* fix IAM role bindings when targeting policy with existing condition
> Release 1.7 asm

- scripts/asm-installer/install_asm
- scripts/asm-installer/tests/fake_gcloud
- scripts/asm-installer/tests/fake_kubectl
- scripts/asm-installer/tests/run_basic_suite
- scripts/asm-installer/tests/run_cli_tests
- scripts/asm-installer/tests/run_install_custom_cert_suite
- scripts/asm-installer/tests/run_migration_suite_citadel
- scripts/asm-installer/tests/run_migration_suite_citadel_prev
- scripts/asm-installer/tests/run_migration_suite_meshca
- scripts/asm-installer/tests/run_migration_suite_meshca_prev
Previously the only action that could be turned off is enabling the
GCP APIs, and all of the other modifications were done all the time.
This commit adds several flags to control different modifications, and
adds an "--enable_all" flag that will allow users to keep the old
behavior. It also changes -e to --enable_all from --enable_apis.
Fixes #207
> Allow granular selection of permissions

- asm/istio/options/hub-meshca.yaml
Same as https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/240
> Redo PR 240 to export GKE_CLUSTER_URL to pilot for Hub overlay

- asm-citadel/cluster/nodepool.yaml
- asm-iap/cluster/nodepool.yaml
- asm/cluster/nodepool.yaml
Fix test failures based on new cluster creation due the changes on GKE apis.
```
Apply configs with Anthos CLI:
+ anthoscli apply -f asm/
I1121 22:11:53.170277     178 main.go:230] reconcile serviceusage.cnrm.cloud.google.com/Service compute.googleapis.com
I1121 22:11:54.562056     178 main.go:230] reconcile serviceusage.cnrm.cloud.google.com/Service container.googleapis.com
I1121 22:11:55.621076     178 main.go:230] reconcile serviceusage.cnrm.cloud.google.com/Service iamcredentials.googleapis.com
I1121 22:11:56.666956     178 main.go:230] reconcile serviceusage.cnrm.cloud.google.com/Service meshca.googleapis.com
I1121 22:11:57.766050     178 main.go:230] reconcile serviceusage.cnrm.cloud.google.com/Service meshtelemetry.googleapis.com
I1121 22:11:58.873913     178 main.go:230] reconcile …
```
> Adding autoRepair and autoUpgrade for anthoscli new cluster creation

- scripts/asm-installer/install_asm
A copy of https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/283 on a new branch master-prow.
This is the effort to make scriptaro integrate with GoB test framework on 1.7.
Changes:
1. _CI_NO_REVISION disables revision-based install, because test framework on 1.7 is not able to support that (need to backport https://github.com/istio/istio/pull/28019/);
1. _CI_ASM_IMAGE_TAG  specifies image tag used for testing;
1. _CI_ISTIOCTL_REL_PATH specifies the istioctl built from the code to be tested.
1. _CI_NO_VALIDATE to skip validation because limited permissions of GoB test runner.
> Add CI related envs to be able to disable revision, specify image tag, and use local build istioctl

- asm/istio/istio-operator.yaml
this is already set by the field meshConfig.defaultConfig.ProxyMetadata.TRUST_DOMAIN, not sure why we have two places here
and actually this is the reason why we saw `dulicate entry for env` error before when we use server-side apply
> remove duplicate trustdomain entry

- scripts/asm-installer/install_asm
Using the auto-set functionality is pointless since it's always overwritten anyways, and in the case that someone is installing ASM on a project different from the current gcloud configured project the messages are misleading.
> Prevent kpt from auto-setting, make info messages clearer

- asm/Kptfile
- asm/istio/options/hub-meshca.yaml
In the case of multiproject ASM installation with Hub, clusters from different GCP projects will be registered within the same Hub of the GCP Environ project. In this case, only GCP Environ project needs to be initialized with Meshapi and we should use environProjectNumber as the PROJECT_NUBMER field of GCP_METADATA.
> Use Environ Project Number in the Hub overlay as GEK_METADATA

- scripts/asm-installer/install_asm
This is for the case that users have existing GKE on GCP clusters in their GCP project running mesh with GKE WIP and they want to try new mesh installation with script and Hub overlay in a new cluster of the same project. By specify both GKE and Hub WIP, we will not break existing mesh with GKE WIP.
Per discussion, we will hold off the multiproject setup for Hub at the master branch. We have a PR for master-prow branch to check the Hub multiproject setup https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/310.
> Update installation script for Hub WIP to be compatible with both GKE and Hub WIP

- asm/Kptfile
- asm/istio/options/hub-meshca.yaml
https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/master/asm/istio/istio-operator.yaml#L29 was introduced for 1.8. Details at https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/278. Thus add the corresponding field in Hub overlay.
> Add TOKEN_AUDIENCES field in the Hub overlay

- asm/istio/options/audit-authorizationpolicy.yaml
Customer may use `--set values.telemetry.v2.stackdriver.configOverride.enable_audit_log=true` to enable AuthorizationPolicy audit logging.
> Enable audit logging with ASM options overlay

- scripts/asm-installer/install_asm
Specifically for those running on a Mac, many people install an updated
version of bash in a different location to avoid stomping on the system
bash. This will help default to the correct shell in more environments.
> Use more compatible shebang

- scripts/asm-installer/install_asm
- scripts/asm-installer/tests/run_cli_tests
Four things split into different commits:
* I somehow missed that it was printing WARNING: ERROR: every time, so fixed that
* Sped up the cli tests by mocking out kpt since we don't test it there
* Check that only-validate isn't combined with any of the enable options in validate_cil_args
* Clarify language around the enable flags in various places.
> Fixes for enable and only_validate

- asm/istio/options/internal-load-balancer.yaml
With the current IstioOperator CR, the installation fails.
```
Error: failed to install manifests: generated config failed semantic validation: port http2/80 in gateway istio-ingressgateway invalid: targetPort is set to 0, which requires root. Set targetPort to be greater than 1024 or configure values.gateways.istio-ingressgateway.runAsRoot=true, port https/443 in gateway istio-ingressgateway invalid: targetPort is set to 0, which requires root. Set targetPort to be greater than 1024 or configure values.gateways.istio-ingressgateway.runAsRoot=true
```
proxyv2 identified ports:
```
Containers:
istio-proxy:
...
Ports:         15020/TCP, 8080/TCP, 8443/TCP, 15090/TCP
```
> ILB - add correct targetPort for ports <1024

- scripts/asm-installer/install_asm
This is the manual cherry pick of https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/310. https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/310 has been tested in the ASM PROW CI workflows.
> Update installation script to support ASM installation with Hub from non hosting project

- scripts/asm-installer/install_asm
We don't generate the control plane yaml when we're installing managed, so
we shouldn't try and print it.
> Fix error when installing managed

- scripts/asm-installer/tests/common.sh
- scripts/asm-installer/tests/run_migration_suite_citadel
- scripts/asm-installer/tests/run_migration_suite_citadel_prev
- scripts/asm-installer/tests/run_migration_suite_meshca
- scripts/asm-installer/tests/run_migration_suite_meshca_prev
For tests where we're migrating from OSS, we never re-label the
namespaces with the correct revision before doing a rolling restart.
With this PR, we put all of the script output info a FIFO and grep out
what the new label is supposed to be, and then label the namespace
properly before performing a restart of the workloads.
> Properly label namespaces in migration tests

- asm/istio/istio-operator.yaml
values.global. trustDomain is deprecated in favor of meshConfig one, however we should set it under meshConfig directly instead of proxymetadata.
> fix trustdomain issue

- asm/Kptfile
- asm/istio/istio-operator.yaml
- asm/istio/istiod-service.yaml
because install_asm will always set them just like PROJECT_ID, also reducing the work of maintaining them in sync from various places with our release version.
https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/master/scripts/asm-installer/install_asm#L17-L20 will be the source of truth of the revision and version.
> Using placeholder for rev and tag

- asm/Kptfile
- asm/istio/istio-operator.yaml
Upgrade ASM in Anthos Sample Deployment to 1.8.1-asm.5
* Sync-ed `asm/istio/istio-operator.yaml` and `asm/canonical-service/controller.yaml, while keeping the custom CPU requests.
* Sync-ed `Kptfile`
> Upgrade ASM in Anthos Sample Deployment to 1.8.1-asm.5

- asm/istio/istio-operator.yaml
Move the autoregistration env var out of values to avoid overriding.
> Modify istio operator config

- scripts/asm-installer/cloudbuild.yaml
- scripts/asm-installer/install_asm
There are certain options that are either more difficult or impossible
to configure properly at install time without the fix applied. There
isn't any harm in applying it beforehand, so we should just do it that
way all the time.
> Apply validation fix before installation

- asm/istio/options/hub-meshca.yaml
To make sure autoregistration env var is not missed when adding hub-meshca overlay.
This env var will not be needed and will be removed in 1.9 release.
> Avoid VM env var override

- asm/vm/install_asm_vm
- Updated util functions to match the implementation in ASM installer
- Updated usage message to match ASM installer
- Remove unused subcommands (`register_gce_instance` and `register_gce_instance_group`)
Tested locally `create_gce_instance_template` still works and script itself does not throw syntax errors.
> [VM Script] Update VM Script to be consistent with ASM installer

- asm/Kptfile
- asm/istio/options/revisioned-istio-ingressgateway.yaml
- scripts/asm-installer/install_asm
I tested with istioctl and kubectl on ingressgateways for a while with different combinations of config structures, and think this is the optimal approach for revision based gateways. Comparing to the original proposal:
- We don't separate the gateways from their original yamls because that introduces one more jump/mapping from an install option to its gateways.
- We still use a single istioctl install command to install a new revision of ingressgateway, istiod, and other resources. But now each revision ingressgateway will get a separate deployment, naming  istio-ingressgateway-ASM_REV.
- We will put the command of switching ingressgateway revisions into our upgrade guide, and let user decide when to change revision to be used. And in the rollback process, user will get a *symmetric* …
> Revision based istio-ingressgateway

- asm/istio/options/managed-control-plane.yaml
- scripts/asm-installer/install_asm
For Gateway, a new env (ISTIO_META_CLOUDRUN_ADDR) is needed.
The value of this env is obtained from mutatingwebhook after
MCP installation.
> Add CLOUDRUN_ADDR for managed control plane

- asm/istio/options/managed-control-plane.yaml
- scripts/asm-installer/install_asm
For Gateway, a new env (ISTIO_META_CLOUDRUN_ADDR) is needed.
The value of this env is obtained from mutatingwebhook after
MCP installation.
> Add CLOUDRUN_ADDR for managed control plane (#393)

- scripts/asm-installer/install_asm
Re-using the same output directory multiple times will cause an error, since we told bash at the very beginning not to let us overwrite files by default. This explicitly lets us do that after a successful installation.
> Overwrite final config when reusing output directory

- scripts/asm-installer/install_asm
- scripts/asm-installer/tests/run_print_config_test
If `csplit` generates more than one file when splitting on the yaml document separator, then remove the yaml file from the list of files to pass to `istioctl` and instead add the split yaml files. Verified that the new test fails before adding the fix.
> Work around istioctl bug with multi component yaml files

- scripts/asm-installer/install_asm
- scripts/asm-installer/tests/fake_gcloud
- scripts/asm-installer/tests/run_cli_tests
If you run the script as a service user instead of having the script authorize the user on your behalf, the wrong account type gets detected.
Fixes #410
> Detect service account better

- scripts/asm-installer/cloudbuild-master.yaml
- scripts/asm-installer/cloudbuild-staging.yaml
- scripts/asm-installer/install_asm
- scripts/asm-installer/tests/common.sh
Instead of having to remember to put `run` everywhere, just override the commands that could have side effects and wrap them with whatever safety mechanisms we want. This fixes a bug in dry-run that incorrectly causes clusters to be considered unreachable. Also adds a small qol change to testing to allow easier local tests without editing the file,
> Wrap commands better

- scripts/asm-installer/install_asm
- scripts/asm-installer/tests/common.sh
Mostly moving a bunch of constant declarations to init. Also added a QOL improvement for local testing (so it's easier to specify `--enable-cluster-labels` when testing new versions)
> Enable specifying alpha builds for testing

- scripts/asm-installer/cloudbuild-master.yaml
There seems to be some sporadic issues that only affect Hub,
since that's not a strong dependency yet we should disable it until
we can figure out what the issue is.
> Remove VM suite from master pre-submit tests

- scripts/asm-installer/install_asm
When reinstalling with an existing folder, options are not converted into yamls in CUSTOM_OVERLAY. This PR should fix it.
> Fix option flags being ignored issue when reinstalling on an existing folder

- scripts/asm-installer/install_asm
- scripts/asm-installer/tests/fake_kubectl
- scripts/asm-installer/tests/run_cli_tests
Use get/describe instead of list, use `nc` to test connectivity since most `kubectl` commands require permissions, re-order logic to avoid extra calls.
> Use less privileged operations during validation

- scripts/asm-installer/release_asm_installer
This lets us manually test out builds before a release. Verified by setting _DEBUG and getting output:
```
<skipped lines>
Branch 'staging-1.8-asm' set up to track remote branch 'staging-1.8-asm' from 'origin'.
Switched to a new branch 'staging-1.8-asm'
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   223  100   223    0     0   1689      0 --:--:-- --:--:-- --:--:--  1689
DEBUG: would have run 'gsutil cp install_asm_staging-1.8 .../install_asm_staging-1.8'
DEBUG: would have run 'gsutil cp install_asm.sha256 .../install_asm_staging-1.8.sha256'
DEBUG: would have run 'gsutil acl ch -u AllUsers:R .../install_asm_staging-1.8 .../install_asm_staging
-1.8.sha256'  
<skipped lines>
```
> Publish staging versions of install_asm

- asm/istio/istio-operator.yaml
Remove the dependency on metadata server because when clusters have customization on DNS or NetworkPolicy, the metadata server is not reachable from the pod.
Tested with my GKE cluster.
> Remove the dependency on metadata server

- asm/Kptfile
- asm/istio/expansion/expose-istiod.yaml
Re-using the existing file so that multiproject multicluster setup can still use the same file.
Manually asking @nmittler for review. Nathan, can you also take a look at the change?
> Allow revisioned istiod to be exposed for discovery

- asm/istio/options/managed-control-plane.yaml
Use gcr.io/wlhe-cr/asm repo to install MCP gateway.
This will let us test the new image.
> Enable new auth for managed control plane gateway

- scripts/asm-installer/install_asm
Without this changing the version with env vars just changes the tarball and not the actual image used by the proxy
> Always override default kpt tag

- scripts/asm-installer/install_asm
*Some* platforms use BSD instead of GNU, so we check for empty files manually instead of handling it with csplit.
> Add BSD csplit compatibility

- asm/vm/asm_vm
- scripts/asm-installer/install_asm
This allows VMs to use a different revision of Istiod during control plane canary upgrade.
/cc @maasen
> [VM Script] Add revisioned Istiod support

- asm/vm/asm_vm
- scripts/asm-installer/install_asm
It may be better for this logic to exist in the agent, but I'm testing against this workaround. 
similar logic: 
https://github.com/istio/istio/blob/386a2dbd7f71c16c0f47820d4f4cc3322ef87e2c/manifests/charts/istio-control/istio-discovery/templates/configmap.yaml#L60
https://github.com/istio/istio/blob/90e498421d5ccdb1c4631c63d8e30dc5d913308f/istioctl/cmd/workload.go#L511-L519
> dont set default revision in meta

- asm/istio/expansion/README.md
- asm/istio/expansion/vm-eastwest-gateway.yaml
- asm/vm/asm_vm
- scripts/asm-installer/tests/common.sh
Add `prepare_cluster` subcommand to:
- validate if expansion gateway is installed. If not, proceed with installation.
- validate if identity provider is installed. If not, proceed with installation.
- enable service mesh feature
Test scripts will be added in a followup PR.
> [VM Script]Prepare cluster for VM workloads

- asm/vm/asm_vm
same as https://github.com/istio/istio/blob/90e498421d5ccdb1c4631c63d8e30dc5d913308f/istioctl/cmd/workload.go#L391
although the template doesn't have `if rev == default`, it assumes the revision isn't passed at all when it is `default`. 
Without this, an ASM installation with `_CI_NO_REVISION` will make the vm script error with `asm_vm: [ERROR]: The environ workload identity is not used in any of your ASM installation in the cluster`
> handle default revision when fetching config map

- scripts/asm-installer/install_asm
- scripts/asm-installer/tests/run_cli_tests
Added/updated tests, also I had to refactor the `can_*` functions because the negative logic was too difficult to read.
> Don't register with -e unless using a feature that requires it

- scripts/asm-installer/install_asm
- scripts/asm-installer/tests/common.sh
- scripts/asm-installer/tests/run_basic_suite_managed
- scripts/asm-installer/tests/setup_longterm_cluster
Production meshconfig API forces us to use a very old Istiod
image version that was created in Jan. The new gateway image
with the new auth is not compatible with that version.
> Switch to staging meshconfig API for managed control plane

- scripts/asm-installer/install_asm
A lot of users miss this in the outro, so this makes the up-front notification more obvious.
> Print flashy message when using tmp directory

- asm/istio/options/vm.yaml
To avoid option file being split.
> Add newline to vm option file

- scripts/asm-installer/install_asm
- scripts/asm-installer/tests/run_migration_suite_meshca
Right now we don't give any guidance for upgrades/migrations if the existing installation uses a custom istiod service as a fix for the OSS validatingwebhook bug. This commit copies the config to a known location and adds steps to the outro.
> Include directions for upgrating validation fix on upgrade/migration

- scripts/asm-installer/asm_vm
istiod uses this in many areas; one thing in particular this breaks (using the latest changes to master post 1.9) is that we won't send DNS for headless services unless this is set. 
I've manually tested this by editing instance metadata/resetting. It fixes DNS resolution of headless services. This change should probably be backported to 1.9 as well.
> set ISTIO_META_CLUSTER_ID in metadata

- asm/istio/options/vm.yaml
Without this, the IstioOperator will overwrite other parts of the installation. 
the istiod deployment/service, mutating webhook configmap/config, validating webhook config and probably a ton of other things end up with `install.operator.istio.io/owning-resource: eastwest` which is incorrect.
> vm eastwest iop should not have name

- asm/Kptfile
- asm/istio/options/revisioned-custom-ingressgateway.yaml
- asm/istio/options/revisioned-istio-ingressgateway.yaml
Cherrypick of 
https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/388/files
https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/431/files
Tested on a cluster by upgrading 1.6 to 1.7
> Backport revisioned ingressgateways to 17

- scripts/asm-installer/install_asm
- scripts/asm-installer/tests/run_cli_tests
We set a few variables for commands that might differ in functionality/location between environments. (e.g. GNU/BSD readlink). There are certain cases where these variables wouldn't properly trigger validation, so we should check for empty values explicitly.
Fixes #539
> Properly validate commands in compatibility vars

- scripts/asm-installer/asm_vm
Boot disk on GCE is required and is always at index 0 of the GCE disk array.
> Only override boot disk name when creating instance template

- scripts/asm-installer/install_asm
All clusters registered to Hub should also have GKE WI enabled to avoid inconsistencies.
> All installations should have GKE WI enabled

- scripts/asm-installer/install_asm
Also a small refactor to group some internal variables together.
> Require workload identity before environ registration

- scripts/asm-installer/install_asm
This PR is part of a set of changes for ASM that involves MCP logging direct to customer project. It mirrors the permissions granted for the monitoring API (metrics writer).
/cc @costinm @qfel
> Add logging writer role to list of MCP SA required perms

- scripts/asm-installer/install_asm
This PR adds a condition so that if the version is properly set, `kpt pkg get` will use the version/tag instead of the branch name.
> Kpt pkg get from tag

- scripts/asm-installer/tests/common.sh
currently the entire `"${NAMESPACE} istio-system asm-system"` will be treated as a single string.
> fix cleanup bug

- scripts/release-asm/common.sh
- scripts/release-asm/pre_release_backfill
Also suppressed error message for legacy `--version`.
> limit the backfill to only semver files

- scripts/asm-installer/install_asm
this in addition allows "roles/container.admin" as the cluster admin. Fixing #588
> count "roles/container.admin" as cluster admin

- asm/istio/istio-operator.yaml
These fields are removed, instead of set to `true`, as they meet the default.
> Enable protocol detection for ASM 1.10

- scripts/asm-installer/install_asm
- scripts/asm-installer/tests/fake_gcloud
- scripts/asm-installer/tests/run_cli_tests
There's no reason to check any other role for project owners.
> Add special case for owner role

- scripts/asm-installer/install_asm
See #619. Hopefully we can get rid of this warning sooner rather than later.
> Add warning for possible uninitialized meshconfig

- scripts/asm-installer/install_asm
Using a more broad pattern for detecting if current gcloud account is a service account or not. Old pattern was missing *@cloudbuild.gserviceaccount.com.
Proposed for for https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/issues/630
> Change service account detection pattern

- asm/istio/options/cni-selinux.yaml
The `istioinstall-cni` container needs a `securityContext` with `Privileged: true` to install `istio-cni` with SELinux enabled.
Related discussion on Istio PR https://github.com/istio/istio/pull/32360
> Install istio-cni with securityContext for SELinux

- docs/developer-guide.md
Now that the initial `bats` integration is merged, we update the dev guide to document the behavior and instructions.
> update dev guide for writing/running tests

- scripts/asm-installer/install_asm
The previous sed command didn't work on MacOS.
Linked issue: #661
> Fix sed command to retrieve project id from workload identity

- asm/istio/options/cni-managed.yaml
Upstream has modified the template in 1.10.
https://github.com/istio/istio/pull/31906
This change is needed in order to use the new image in master branch
Scritaro. This change doesn't need to be cherry-picked to 1.9
since it's not affected.
> Adjust container commnad path for istio-cni-repair

- asm/istio/istio-operator.yaml
- asm/istio/options/hub-meshca.yaml
- scripts/asm-installer/asm_vm
Upgrade from 1.9->1.10 should not hit the permission issue again as istio-reader clusterrole has the workloadentry read access.
Also remove the autoregistration env var as it is enabled by default.
> Enable cross cluster workload entry again

- scripts/asm-installer/install_asm
Hi team,
Current install_asm script is hard to debug when it failed because it won't show the actual commands failed.
This is just 2 line modification to show the command executed when it failed.
> Update retry() to show executed command when it failed

- asmcli/Dockerfile
- asmcli/cloudbuild-main.yaml
Update the docker file to use the /workspace directly without having to copy. Also, add steps to the cloudbuild yaml to perform `npm install` and run unit tests.
> Update docker file

- scripts/asm-installer/install_asm
I confirmed with GKE networking team that workload identity should imply PTP CNI enablement, which makes network policy enablement not necessary for Istio CNI. This is an internal tracking bug for more information: [b/189281678](https://b.corp.google.com/issues/189281678).
> Revert "Enable Network Policy for MCP with CNI (#668)"

- asm/Kptfile
- asm/istio/options/hub-meshca.yaml
- scripts/asm-installer/install_asm
For ASM 1.10
- GKE-on-GCP: The Mesh CA with Environ installation option will be kept unchanged, which installs the cluster with the old HUB WIP.  
- VM: new Hub WIP and its IDP will be used. @JimmyCYJ let me know if you want to keep it the same as GKE-on-GCP to use the old Hub WIP. 
- Onprem: new Hub WIP and its IDP will be used.
> make --hub_meshca behavior consistent between ASM 1.9 and ASM 1.10 for GKE-on-GCP

- scripts/asm-installer/Dockerfile
- scripts/asm-installer/install_asm
- scripts/asm-installer/tests/run_cli_tests
With the upcoming 1.0 release of `kpt`, we need to make sure that users get a version that works with the config here. This will download `kpt` if it's necessary for the action taken (install vs print config etc.) and one of the following:
* the system version is too new
* there isn't a `kpt` binary in the specified OUTPUT_DIR already
> Download kpt when necessary

- asmcli/tests/setup_longterm_cluster
* Only run cleanup actions when the cluster exists
* Don't setup the create-mesh clusters every time, it's slow and we don't run the test automatically
> Fix setup script

- asm/istio/options/cni-managed.yaml
Same change as https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/809, but for asmcli.
> Fix token audience for managed CNI.

- asmcli/asmcli
- asmcli/commands/create-mesh.sh
- asmcli/lib/context.sh
- asmcli/lib/validate.sh
The subcommand can accept N kubeconfig files, each of which is expected
to contain a default context that will be the ONLY context used. The UX
for N clusters would be to supply N differennt files, each of which will
have a default context set to the corresponding target cluster.
>  Add kubeconfig (GKE only) support to create-mesh subcommand

- asmcli/asmcli
- asmcli/commands/help.sh
- asmcli/lib/parse.sh
- asmcli/lib/validate.sh
this PR does
1. show deprecation message for `--only-validate`
2. fix the parsing bug where user gets no meaningful info after the parsing is delegated to each subcommand.
> deprecate --only-validate and fix parse bug 

- asmcli/asmcli
- asmcli/components/ca/citadel.sh
- asmcli/lib/validate.sh
Citadel without custom certs should still configure the overlay
> Fix citadel validation/config

- scripts/asm-installer/install_asm
Amending ASM installation scripts for GA integration with Google [CAS](https://cloud.google.com/certificate-authority-service)
* Changed the environments supported (Managed Control Plane is also supported)
* Changed the IAM privileges required for ASM workloads to request certificates and trustAnchors from CAS
Main purpose of making these changes here is to backport these changes if needed into release-1.10-asm
> Private CA GA integration changes

- asm/istio/options/managed-control-plane-webhooks.yaml
This should be merged to 1.11 branch. It can be merged to 1.10, but does nothing. It MUST not be merged to 1.9.
> Add telemetry to validating webhook

- asmcli/asmcli
- asmcli/commands/install.sh
- asmcli/components/ca/citadel.sh
Moves the Citadel installation logic to the component file, adds if statement for custom certs.
> Only install custom certificates sometimes with Citadel

- asmcli/asmcli
- asmcli/components/ca/citadel.sh
This will fail with a somewhat cryptic message if you try to upgrade ASM and specify custom certificates on an existing installation with custom certificates.
> Improve error message for duplicate custom certs

- asmcli/asmcli
- asmcli/commands/validate.sh
- asmcli/lib/validate.sh
currently `validate_hub` comes before `prepare_environment`, which causes the fleet info to not be populated correctly since `kubectl` is not configured.
> move validate_hub after configure_kubectl

- asmcli/asmcli
- asmcli/commands/experimental/vm.sh
- asmcli/lib/checks.sh
currently the calls to the api-server experiences some flakes and give errors like:
```
error: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```
this issue does not affect prod clusters but does introduce a lot of test flakes. This PR adds retries to the api-resources calls.
> add retry to kubectl api-resources

- asmcli/asmcli
- asmcli/components/control-plane/in-cluster.sh
the tests do not cover in #884 since `USE_HUB_WIP` is default to be true. Manually tested with 
```
_CI_ASM_PKG_LOCATION=asm-staging-images _CI_ASM_KPT_BRANCH=main USE_HUB_WIP=0 ./asmcli/asmcli install --kubeconfig ~/.kube/config -v -e --only-enable
```
and it worked.
> fix the curl quotation

- asmcli/asmcli
- asmcli/lib/parse.sh
`asmcli x install` does not properly populate the revision label global.
> fix the revision label bug

- asmcli/asmcli
- asmcli/commands/experimental.sh
- asmcli/commands/experimental/help.sh
- asmcli/commands/experimental/mcp-migrate-check.sh
Tested locally with this output:
```
./asmcli/asmcli x mcp-migrate-check -f test 
asmcli: Downloading ASM..
Generating equivalent configuration for Anthos Service Mesh managed control plane...
Migrating MeshConfig settings...
✔ Wrote MeshConfig to asm-generated-configs/meshconfig.yaml.
Migrating gateway deployments...
Checking configuration compatibility...
! Found unsupported configurations:
Components.Base: not configurable in managed control plane
Components.Pilot: not configurable in managed control plane
Hub=gcr.io/gke-release/asm: not configurable in managed control plane
Tag=1.10.4-asm.6: not configurable in managed control plane
Actions required to migrate:
! Found potentially unsupported configurations; review warnings above before proceeding
- Found custom mesh configuration …
```
> Add experimental mcp-migrate-check

- asm/istio/options/cni-gke-autopilot.yaml
* Add no-connect annotation, which blocks exec into the CNI pod.
* Disable CNI reinstall. This will make migration easy in the future.
> Update CNI autopilot overlay.

- asmcli/asmcli
- asmcli/components/control-plane/managed.sh
- asmcli/lib/context.sh
- asmcli/lib/parse.sh
- asmcli/tests/run_basic_suite_managed
Remove the necessities of setting `cni-managed` option when installing managed ASM.
cc @mandarjog
> Make CNI always on at managed ASM.

- asmcli/asmcli
- asmcli/commands/install.sh
This PR fixes the following problems of ASM CAS installation:
- add-iam-policy-binding should use the CA pool as its argument, instead of the CA name (in the form of "projects/project_name/locations/ca_region/caPools/ca_pool").
- The role "roles/privateca.auditor" should be added to the member "group:${WORKLOAD_IDENTITY}", instead of "serviceAccount:${WORKLOAD_IDENTITY}". When the role "roles/privateca.auditor" is added to "serviceAccount:${WORKLOAD_IDENTITY}", an error occurs.
- The --project is needed to specify the project ID.
> Fix the ASM CAS installation

- asmcli/asmcli
- asmcli/commands/create-mesh.sh
the scripts now successfully registeres the cluster-2 from project `zhengzhe-anthos-test` to `zhengzhe-test-project`
```
2021-09-14T00:36:55.856999 asmcli: Registering the cluster zhengzhe-anthos-test/us-central1-c/cluster-2 as 1631579815789678555...
2021-09-14T00:36:55.999593 asmcli: Running: '/usr/local/google/home/zhengzhey/google-cloud-sdk/bin/gcloud container hub memberships register 1631579815789678555 --project=zhengzhe-test-project --gke-uri=https://container.googleapis.com/v1/projects/zhengzhe-anthos-test/zones/us-central1-c/clusters/cluster-2 --enable-workload-identity'
2021-09-14T00:36:56.066014 asmcli: -------------
kubeconfig entry generated for cluster-2.
Waiting for membership to be created...
...................done.
Created a new membership …
```
> fix the bug where it should be fleet_id

- asm/canonical-service/controller.yaml
This version should be used regardless of ASM version
> Update hardcoded version for canonical-service-controller

- asm/istio/options/cni-managed.yaml
Istio cni does not need to run with hostNetwork. This has already been removed at master and 1.11.
> Remove hostNetwork from cni-managed

- asmcli/asmcli
- asmcli/lib/installation_dependencies.sh
The current sed command doesn't match memberships registered to GKE Hub's autopush instance (example: `//autopush-gkehub.sandbox.googleapis.com/projects/43552690995/locations/global/memberships/ci-tbf1fb9087924ec3`).
Testing:
$ echo $TEST_URI
> "//gkehub.googleapis.com/projects/andash-on-prem/locations/global/memberships/ci-tbf1fb9087924ec3"
$ echo $TEST_URI_AUTOPUSH
> "//autopush-gkehub.sandbox.googleapis.com/projects/43552690995/locations/global/memberships/ci-tbf1fb9087924ec3"
$ echo $TEST_URI | sed 's/^\"\/\/\(autopush-\)\{0,1\}gkehub\(.sandbox\)\{0,1\}.googleapis.com\/projects\/\(.*\)\/locations\/global\/memberships\/\(.*\)\"$/\4/g'
> ci-tbf1fb9087924ec3
$ echo $TEST_URI_AUTOPUSH | sed 's/^\"\/\/\(autopush-\)\{0,1\}gkehub\(.sandbox\)\{0,1\}.googleapis.com\/projects\/\(.*\)\/locations\ …
> Make asmcli resilient to Hub autopush registration

- asm/Kptfile
- asmcli/asmcli
- asmcli/components/control-plane/in-cluster.sh
- asmcli/components/control-plane/managed.sh
This PR implements
- Set PROJECT_NUMBER within GCP_METADATA with cluster local project gcloud.project.projectNumber. This implies the mesh use cluster local project P4SA. 
- Initialize cluster local project with both Fleet WIP and GKE WIP. This will allow Fleet WI impersonate Cluster Local Project P4SA.
> Use Cluster Local Project P4SA with Fleet WIP

- asmcli/asmcli
- asmcli/components/control-plane/managed.sh
- asmcli/lib/util.sh
Check the return code when calling runIstiod, fail if it's not a 200.
When successful, it logs this:
```
2021-09-30T20:36:30.992145 asmcli: Running: 'curl --write-out %{http_code} --silent --show-error --output /tmp/tmp.uMF7JCraIx --request POST https://meshconfig.googleapis.com/v1alpha1/projects/samer-asm-test2/locations/us-central1-b/clusters/somecluster:runIstiod --data {} --header X-Server-Timeout: 600 --header Content-Type: application/json -K /dev/fd/63'
2021-09-30T20:36:31.022427 asmcli: Running: '/usr/bin/gcloud --project=samer-asm-test2 auth print-access-token'
2021-09-30T20:36:31.041526 asmcli: -------------
2021-09-30T20:36:31.073035 asmcli: -------------
{}
```
This is what it looks like when it fails:
```
2021-09-30T20:40:35.943337 asmcli: Provisioning control plane... …
```
> Check return code from runIstiod call

- asmcli/asmcli
- asmcli/components/control-plane/managed.sh
Instead of just checking for asm-managed, check for asm-managed-rapid,
asm-managed, and asm-managed-stable in that order, and use the first
webhook that exists as the validating webhook.
This will allow the managed control plane to return a subset of
revisions (for code that uses new features, e.g. fleet memberships),
instead of always needing to create the asm-managed revision.
Output:
```
2021-10-04T21:39:05.260052 asmcli: Running: '/usr/bin/kubectl --kubeconfig asm_kubeconfig --context gke_samer-asm-test2_us-central1-b_somecluster get mutatingwebhookconfiguration istiod-asm-managed-rapid -ojson'
2021-10-04T21:39:05.335782 asmcli: -------------
2021-10-04T21:39:05.593078 asmcli: Using the following managed revision for validating webhook: asm-managed-rapid
2021-10-04T21:39:05.792370 …
```
> Check all possible managed revisions for the validation webhook

- asmcli/asmcli
- asmcli/commands/create-mesh.sh
In certain situations the pods may not exist or not have the correct label (e.g. remote control plane). We shouldn't hard-fail create-mesh in these circumstances.
> Don't fail create-mesh on inability to patch configmaps

- asmcli/asmcli
- asmcli/lib/util.sh
Before, when not using a non-GCP platform, we'd ignore what's passed in for --network_id and use "default". After this we'll use what's set in the flag and leave unset otherwise.
> Respect --network_id for non-GCP platforms

- asmcli/asmcli
- asmcli/lib/checks.sh
If we're on GCP and using a connect gateway, then we know that the membership exists and can parse this info since we must be connecting via a kubeconfig.
> Parse info from membership sometimes

- asmcli/asmcli
- asmcli/lib/installation_dependencies.sh
- asmcli/lib/util.sh
This will do two things:
1) Use the --enable-gcp-iam-roles to automatically create cross project IAM bindings if needed
2) Create the mesh service account binding cross project if needed, also respecting the --enable-gcp-iam-roles flag
> create cross-project mesh service account

- asmcli/asmcli
- asmcli/commands/help.sh
- asmcli/lib/parse.sh
This is for fixing the vpcsc test failure on GoB when getting the most recent asmcli.
> Add use_vpcsc flag to the main asmcli managed command

- asmcli/asmcli
- asmcli/commands/create-mesh.sh
The `--name` flag should match the cluster name used for install.
> fix create-mesh cluster names

- asmcli/asmcli
- asmcli/lib/checks.sh
In multicloud clusters, identity provider resource name include project number instead of project id.
> Allow project number in identity provider for multicloud cluster

- asm/Kptfile
- asmcli/asmcli
- asmcli/commands/create-mesh.sh
- asmcli/commands/help.sh
Also, special case -v and -h to make sure we don't break expectations now that we're enforcing the first argument be the fleet_id.
> Support output dir with create-mesh

- samples/online-boutique/kubernetes-manifests/deployments/adservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/cartservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/checkoutservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/currencyservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/emailservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/frontend.yaml
- samples/online-boutique/kubernetes-manifests/deployments/loadgenerator.yaml
- samples/online-boutique/kubernetes-manifests/deployments/paymentservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/productcatalogservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/recommendationservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/shippingservice.yaml
Use the latest version of `onlineboutique` with the fix for CVE in log4j
https://github.com/GoogleCloudPlatform/microservices-demo/releases/tag/v0.3.3
This is leveraged for example here: https://cloud.google.com/service-mesh/docs/onlineboutique-install-kpt
> security: update `onlineboutique` to latest v0.3.3

- asm/istio/options/distroless-proxy
With the [recent announcement](https://cloud.google.com/service-mesh/docs/release-notes#December_09_2021) about the option to leverage a distroless image for the proxy, I'm wondering if we could add this file which will allow to use the `--option distroless-proxy` parameter when using `asmcli` instead of having to create that file like explained here https://cloud.google.com/service-mesh/docs/unified-install/options/enable-optional-features#distroless_proxy_image.
> Create `distroless-proxy` option

- samples/online-boutique/kubernetes-manifests/deployments/adservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/cartservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/checkoutservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/currencyservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/emailservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/frontend.yaml
- samples/online-boutique/kubernetes-manifests/deployments/loadgenerator.yaml
- samples/online-boutique/kubernetes-manifests/deployments/paymentservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/productcatalogservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/recommendationservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/shippingservice.yaml
Following up https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/1077, we need to upgrade the `onlineboutique` sample to [v0.3.4](https://github.com/GoogleCloudPlatform/microservices-demo/releases/tag/v0.3.4) to get the latest `log4j` 2.16.
> security: update `onlineboutique` to latest v0.3.4

- asmcli/asmcli
- asmcli/commands/validate.sh
- asmcli/lib/checks.sh
- asmcli/lib/validate.sh
Workload identity should be enabled on Node pools. This PR adds a check to make sure the WI is enabled at node-level which is a requirement for Managed ASM (the cluster-level WI will continued to be updated in the script if it's not enabled). If the user create the cluster without `--workload-pool` option but later update the cluster, the existing node pool will not be touched. (https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#enable_on_cluster) 
> To enable Workload Identity on an existing cluster, modify the cluster with the following command:
gcloud container clusters update CLUSTER_NAME \
--workload-pool=PROJECT_ID.svc.id.goog
Existing node pools are unaffected; new node pools default to --workload-metadata=GKE_METADATA.
Test result: 
Updated cluster with node …
> validate node pool workload identity

- asm/control-plane-revision/cr_rapid.yaml
- asm/control-plane-revision/cr_regular.yaml
- asm/control-plane-revision/cr_stable.yaml
The default "false" will lead the user to think that the CNI is disabled, which is almost always not true since CNI should now be enabled for any installation path. Therefore, defaulting to an empty string could reduce confusion.
> managed cni enablement default to empty string

- asmcli/asmcli
- asmcli/asmcli.sh
- asmcli/lib/checks.sh
- asmcli/lib/validate.sh
- asmcli/tests/lib/validate.bats
autopilot is causing failures since it does not allow access to the node pools. Skip autopilot clusters during validation.
> skip autopilot clusters when validating node pool worklaod identity

- samples/online-boutique/kubernetes-manifests/deployments/adservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/cartservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/checkoutservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/currencyservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/emailservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/frontend.yaml
- samples/online-boutique/kubernetes-manifests/deployments/loadgenerator.yaml
- samples/online-boutique/kubernetes-manifests/deployments/paymentservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/productcatalogservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/recommendationservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/shippingservice.yaml
Upgrade onlineboutique sample to v0.3.5 https://github.com/GoogleCloudPlatform/microservices-demo/releases/tag/v0.3.5
2 main reasons:
- Updated Log4j to 2.17.1
- Turned off GCP integration by default - which land to an issue if not here when deploying ASM on non-GKE-on-GCP clusters by following this doc: https://cloud.google.com/service-mesh/docs/onlineboutique-install-kpt
> `onlineboutique` - v0.3.5

- asmcli/asmcli
- asmcli/lib/validate.sh
- asmcli/tests/unit_test_common.bash
```
./asmcli/asmcli install --kubeconfig ~/.kube/config  --managed -e -v  
...
2022-01-20T05:18:18.347866 asmcli: Running: '/tmp/tmp.5S59tHpKvC/kpt cfg set asm anthos.servicemesh.use-managed-cni true'
2022-01-20T05:18:18.415376 asmcli: -------------
asm/
set 3 field(s) of setter "anthos.servicemesh.use-managed-cni" to value "true"
...
```
> autopilot should default enable managed CNI

- asmcli/asmcli
- asmcli/asmcli.sh
RHEL for whatever reason now includes this by default and it breaks a lot of stuff, including asmcli.
> Unset which

- samples/online-boutique/kubernetes-manifests/deployments/adservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/cartservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/checkoutservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/currencyservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/emailservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/frontend.yaml
- samples/online-boutique/kubernetes-manifests/deployments/loadgenerator.yaml
- samples/online-boutique/kubernetes-manifests/deployments/paymentservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/productcatalogservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/recommendationservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/shippingservice.yaml
Upgrade onlineboutique sample to v0.3.6 https://github.com/GoogleCloudPlatform/microservices-demo/releases/tag/v0.3.6
A new issue was discovered and fixed when deploying ASM on non-GKE-on-GCP clusters by following this doc: https://cloud.google.com/service-mesh/docs/onlineboutique-install-kpt
> `onlineboutique` - v0.3.6

- asmcli/asmcli
- asmcli/commands/install.sh
Fix issue #1117 : We print out the revision label in the outro, but we don't change the revision label based on the type of installation has been launched. For instance, --managed with --channel rapid should return --asm-managed-rapid, asm-managed is return instead.
> Fix issue #1117

- asmcli/asmcli
- asmcli/components/control-plane/managed.sh
install asm and cat the applied configmap in the output directory
```
cat /tmp/tmp.coZvKvhKvj/mcp_configmap.yaml 
---
apiVersion: v1
kind: ConfigMap
metadata:
name: asm-options
namespace: istio-system
data:
ASM_OPTS: "CNI=on;"
```
update the config map in the cluster to be `CNI=off`
```
k edit cm asm-options -n istio-system
configmap/asm-options edited
```
install and cat again
```
cat /tmp/tmp.coZvKvhKvj/mcp_configmap.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
name: asm-options
namespace: istio-system
data:
ASM_OPTS: "CNI=off;;"
```
Double-check the in-cluster CM
```
k get cm asm-options -n istio-system -oyaml
apiVersion: v1
data:
ASM_OPTS: CNI=off;;
kind: ConfigMap
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: | …
```
> asmcli should respect CNI=off

- asmcli/asmcli
- asmcli/components/ca/citadel.sh
This will fix the federated token exchange issue when stackdriver option is used with Citadel + Fleet registration on the cluster. I have verified the fix on the Anthos on AWS V2 cluster.
> fix the stackdriver option for Citadel

- asmcli/asmcli
- asmcli/lib/context.sh
This is a pretty common point of friction when following `export FOO` steps in installation/demo guides. This at least makes it more visible what's going on.
> Print opts pulled from env vars

- asm/Kptfile
- asm/istio/options/cni-managed.yaml
- asmcli/asmcli
- asmcli/asmcli.sh
- asmcli/commands/validate.sh
- asmcli/components/control-plane/managed.sh
- asmcli/lib/checks.sh
- asmcli/lib/config.sh
- asmcli/lib/validate.sh
- asmcli/tests/lib/validate.bats
This PR fixes 2 bugs and changes 1 behavior
1. it fixes the bug when the function `is_autopilot` is called too early to always return an error. If `asmcli` detects the cluster is autopilot, it shouldn't ever attempt to apply anything to the `kube-system`. It should always use managed CNI. The user shouldn't need to supply the `--use_managed_cni` flag. I moved that function to the `validate_control_plane` and refactored the validation for autopilot.
2. it fixes the bug that when we check for the node pool WI, we assumed only 1 node pool is present. It would directly fail on clusters with multiple node pools. Changed it to be a loop.
3. it changes the behavior that when the user's cluster does not have node pool WI enabled, it shouldn't just abort. It would set the env var in the …
> skip cni install if node pool wi is not enabled

- asmcli/asmcli
- asmcli/commands/create-mesh.sh
This PR fixes name of istio remote secret created by `asmcli create-mesh` subcommand.
In using multicluster service mesh, inter-cluster routing by `topology.istio.io/cluster` label in DestinationRule does not work. It causes HTTP 503 response with `no healthy upstream`.
This problem seems caused by mismatch between cluster name and istio remote secret name.
Cluster name is generated by `asmcli install` subcommand and it is form as `cn-PROJECT_ID-LOCATION-CLUSTER_NAME`.
But, for name of istio remote secret generated by `asmcli create-mesh` subcommand, it forms `istio-remote-secret-gke-PROJEC_ID-LOCATION-CLUSTER_NAME`.
This PR changes `SECRET_NAME` as `cn-PROJECT_ID-LOCATION-CLUSTER_NAME` form if remote cluster is GKE.
> Fix name of istio remote secret for GKE cluster.

- asmcli/asmcli
- asmcli/components/control-plane/managed.sh
Manual test result on a cluster without Nodepool WI. Note that CNI=on is not set.
```
2022-05-03T21:24:01.031694 asmcli: *****************************
2022-05-03T21:24:01.111655 asmcli: Successfully installed ASM.
➜  k get cm asm-options -n istio-system -oyaml
apiVersion: v1
data:
ASM_OPTS: ""
kind: ConfigMap
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"v1","data":{"ASM_OPTS":""},"kind":"ConfigMap","metadata":{"annotations":{},"name":"asm-options","namespace":"istio-system"}}
creationTimestamp: "2022-05-03T21:23:53Z"
name: asm-options
namespace: istio-system
resourceVersion: "14060028"
uid: fd2a43fd-fd09-4db2-85bd-73bb086a4dc4
```
> fix the bug to not set the cni=on if no nodepoll WI

- asm/istio/options/ca-migration-meshca.yaml
kpt configurations should not modify this option file which is intended to be appended to the list of trustDomains trusted by the control plane
> ca migration trustDomain Alias fix

- asmcli/asmcli
- asmcli/commands/validate.sh
- asmcli/components/ca/managed-cas.sh
Enabling workload certificate feature on a cluster will result in the cluster restarting and the cluster becoming unreachable for minutes. The PR waits for the k8s cluster becoming reachable and checks the workload certificate enablement status before proceeding with the installation.
> Wait for workload certificate enablement

- asmcli/asmcli
- asmcli/lib/context.sh
This prevents basic auth info from inadvertently being put somewhere visible.
> Don't print HTTPS_PROXY value to terminal

- asmcli/asmcli
- asmcli/lib/installation_dependencies.sh
- asmcli/lib/validate.sh
- asmcli/tests/unit_test_common.bash
We made this required in February, but there's one code path that still might erroneously print this message.
> Remove incorrect warning message

- asmcli/asmcli
- asmcli/lib/checks.sh
GKE Autopilot enforcing managed CNI:
```
2022-12-20T22:36:49.881961 asmcli: Running: '/usr/bin/gcloud container clusters describe autopilot-cluster-1 --region us-central1 --project zhengzhe-test-project --format json'
2022-12-20T22:36:49.931482 asmcli: -------------
2022-12-20T22:36:51.099157 asmcli: [WARNING]: Managed CNI is required to continue installing managed ASM on GKE Autopilot.
2022-12-20T22:36:51.175913 asmcli: [WARNING]: Confirm or pass --use-managed-cni flag to asmcli.
Continue? [y/N] y
```
GKE Standard installing local CP:
```
2022-12-20T22:40:32.059301 asmcli: -------------
components.pilot.k8s.replicaCount should not be set when values.pilot.autoscaleEnabled is true
✔ Istio core installed                                                                  
✔ Istiod installed …
```
> fix the bug when the cluster info is not populated

- asm/canonical-service/controller.yaml
A customer has reported that v0.5 has security vulnerabilities, and newer versions have been available for quite a while.  Tested and confirmed that the controller works with the new version.
> Bump kube-rbac-proxy version

- asm/istio/istio-operator.yaml
- asmcli/asmcli
- asmcli/lib/config.sh
For Control plane Authentication, Istiod can authenticate the sidecar/gateways using JWT. Requiring Istiod to authenticate the dataplane using the mTLS cert signed by the CA is unnecessary.
> Remove fetching spiffe bundles from endpoints for default template

- asmcli/asmcli
- asmcli/commands/create-mesh.sh
- scripts/migration/migrate-to-asm
Patches for https://github.com/istio/istio/pull/46051 and https://github.com/istio/istio/pull/46257
> Use top level `istioctl` commands for `create-remote-secret` and `tag`

- asmcli/asmcli
- asmcli/lib/parse.sh
Allowing this gives the wrong impression that GKE and ASM channels are independent, which is useless at best and dangerous at worst. We shouldn't be making it easier for customers to run nonstandard environments.
> Do not support channel selection via CLI args

- asm/Kptfile
- asmcli/asmcli
- asmcli/asmcli.sh
- asmcli/commands/create-mesh.sh
- asmcli/commands/help.sh
- asmcli/lib/config.sh
- asmcli/lib/installation_dependencies.sh
- asmcli/lib/util.sh
- scripts/migration/migrate-to-asm
- scripts/release-asm/common.sh
* Bump revision 1.18.2-asm.0 (#1481)
* Update release script (#1483)
* Use top level `istioctl` commands for `create-remote-secret` and `tag` (#1484)
Patches for https://github.com/istio/istio/pull/46051 and https://github.com/istio/istio/pull/46257
* Revert Off-GCP metadata population (#1485)
* Add --working-dir alias for output directory
* Add --working-dir alias for output directory
* Update test case to utilize --working-dir alist for output dir
* Populate GCP_METADATA by membership monitoring config
* Add local variables for lint
* Address line-variable error
* Revert "Populate GCP_METADATA by membership monitoring config"
This reverts commit b3372bd6c4dbaed869ad4006a9a41a5352bda9ec.
* Do not support channel selection via CLI args (#1488)
Allowing this gives the wrong impression that …
> Merge staging-1.18 to release-1.18

- asmcli/asmcli
- asmcli/lib/installation_dependencies.sh
For ca=gcp_cas, since a base requirement is that the ca-pools need to be setup before installing control plane (and we validate that ca-pool config), no need to have a duplicate check to see if privateca.googleapis.com is enabled
> Adjust required dependencies for privateca.googleapis.com

- asmcli/asmcli
- asmcli/commands/create-mesh.sh
- asmcli/lib/util.sh
This fixes some validation that depends on external yaml configuration that would otherwise get skipped and cause incorrect error messages.
> Organize kpt files even in offline mode

- asmcli/Dockerfile
Adding `--allow-releaseinfo-change` flag as per https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/378
> [1.18]Fix cloud-sdk:slim

- asmcli/Dockerfile
Adding --allow-releaseinfo-change flag as per https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/378
> [1.19] Fix cloud-sdk:slim

- asmcli/Dockerfile
Adding `--allow-releaseinfo-change` flag as per https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/378
> [1.20] Fix cloud-sdk:slim

- samples/online-boutique/kubernetes-manifests/deployments/adservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/cartservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/checkoutservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/currencyservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/emailservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/frontend.yaml
- samples/online-boutique/kubernetes-manifests/deployments/loadgenerator.yaml
- samples/online-boutique/kubernetes-manifests/deployments/paymentservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/productcatalogservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/recommendationservice.yaml
- samples/online-boutique/kubernetes-manifests/deployments/shippingservice.yaml
* See Google-internal bug: [b/324253531](http://b/324253531).
* This repo uses an old version of Online Boutique (v0.3.6) — we should update it to the latest (v0.9.0).
* We are:
* updating the Online Boutique microservice images to `v0.9.0`.
* updating the other parts of `Deployment` resources which changed between `v0.3.6` and `v0.9.0`.
* Unfortunately, we don't have automated tests for these changes.
* I manually tested the tutorial at [Deploying the Online Boutique sample application](https://cloud.google.com/service-mesh/docs/onlineboutique-install-kpt) using the changes from this pull-request (without the ASM parts):
```bash
kpt pkg get \
https://github.com/NimJay/anthos-service-mesh-packages.git/samples/online-boutique@nimjay-online-boutique-v0.9.0 \
online-boutique
```
* When we …
> Update Online Boutique sample to v0.9.0

- asm/istio/options/ca-migration-meshca.yaml
This PR removes the flag that prevents the pods from startup when MeshCA is selected.
> Removed EnableCAServer flag from migration option
